# Generated by Django 5.2 on 2025-11-08 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_anual_efectiva', models.DecimalField(decimal_places=2, default=5.0, help_text='Tasa anual efectiva (EA) en porcentaje', max_digits=5)),
                ('fecha_vigencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tasa',
                'verbose_name_plural': 'Configuraciones de Tasas',
                'ordering': ['-fecha_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_credito', models.CharField(editable=False, help_text='ID único y legible para el crédito (ej. CR-2024-00001)', max_length=20, unique=True)),
                ('linea', models.CharField(choices=[('EMPRENDIMIENTO', 'Emprendimiento'), ('LIBRANZA', 'Libranza')], max_length=30)),
                ('estado', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], default='SOLICITUD', max_length=30)),
                ('documento_enviado', models.BooleanField(default=False, help_text='Indica si el pagaré ha sido enviado para firma.')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, help_text='Monto solicitado por el cliente', max_digits=10)),
                ('plazo_solicitado', models.IntegerField(help_text='Plazo solicitado en meses')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto aprobado por el analista (puede diferir del solicitado)', max_digits=10, null=True)),
                ('plazo', models.IntegerField(blank=True, help_text='Plazo aprobado en meses', null=True)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual (%)', max_digits=5, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, help_text='Comisión de estudio del crédito', max_digits=10, null=True)),
                ('iva_comision', models.DecimalField(blank=True, decimal_places=2, help_text='IVA sobre la comisión (19%)', max_digits=10, null=True)),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, help_text='Total a pagar (capital + intereses + comisión + IVA)', max_digits=12, null=True)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo pendiente por pagar', max_digits=12, null=True)),
                ('capital_pendiente', models.DecimalField(blank=True, decimal_places=2, help_text='Capital pendiente por amortizar (sin intereses)', max_digits=12, null=True)),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de la cuota fija mensual', max_digits=10, null=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, help_text='Fecha de vencimiento de la próxima cuota', null=True)),
                ('fecha_desembolso', models.DateTimeField(blank=True, help_text='Fecha en la que se realizó el desembolso', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CreditoEmprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo del solicitante')),
                ('numero_cedula', models.CharField(max_length=20, verbose_name='Número de cédula')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('celular_wh', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('direccion', models.TextField(verbose_name='Dirección de residencia')),
                ('estado_civil', models.CharField(max_length=20, verbose_name='Estado civil')),
                ('numero_personas_cargo', models.IntegerField(verbose_name='Número de personas a cargo')),
                ('nombre_negocio', models.CharField(max_length=100, verbose_name='Nombre del negocio')),
                ('ubicacion_negocio', models.TextField(verbose_name='Ubicación del negocio')),
                ('tiempo_operando', models.CharField(max_length=50, verbose_name='Tiempo operando')),
                ('dias_trabajados_sem', models.IntegerField(verbose_name='Días trabajados por semana')),
                ('prod_serv_ofrec', models.TextField(verbose_name='Productos/servicios que ofrece')),
                ('ingresos_prom_mes', models.CharField(max_length=50, verbose_name='Ingresos promedio mensuales')),
                ('cli_aten_day', models.IntegerField(verbose_name='Clientes atendidos por día')),
                ('inventario', models.CharField(max_length=2, verbose_name='¿Tiene inventario?')),
                ('nomb_ref_per1', models.CharField(max_length=100, verbose_name='Nombre referencia personal 1')),
                ('cel_ref_per1', models.CharField(max_length=20, verbose_name='Celular referencia personal 1')),
                ('rel_ref_per1', models.CharField(max_length=50, verbose_name='Relación referencia personal 1')),
                ('nomb_ref_cl1', models.CharField(max_length=100, verbose_name='Nombre referencia cliente 1')),
                ('cel_ref_cl1', models.CharField(max_length=20, verbose_name='Celular referencia cliente 1')),
                ('rel_ref_cl1', models.CharField(max_length=50, verbose_name='Relación referencia cliente 1')),
                ('ref_conoc_lid_com', models.CharField(max_length=2, verbose_name='¿Conoce al líder comunitario?')),
                ('foto_negocio', models.FileField(help_text='Solo se permiten archivos PDF', upload_to='fotos_negocios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('desc_fotos_neg', models.TextField(verbose_name='Descripción de las fotos del negocio')),
                ('tipo_cta_mno', models.CharField(max_length=20, verbose_name='Tipo de cuenta de mano')),
                ('ahorro_tand_alc', models.CharField(max_length=2, verbose_name='¿Tiene ahorro en tanda/alcancía?')),
                ('depend_h', models.CharField(max_length=2, verbose_name='¿Tiene dependientes?')),
                ('desc_cred_nec', models.TextField(verbose_name='Descripción de por qué necesita el crédito')),
                ('redes_soc', models.CharField(max_length=2, verbose_name='¿Tiene redes sociales?')),
                ('fotos_prod', models.CharField(max_length=2, verbose_name='¿Tiene fotos de productos?')),
                ('puntaje', models.IntegerField(blank=True, help_text='Puntaje de evaluación del crédito (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones_analista', models.TextField(blank=True, help_text='Observaciones del analista durante la evaluación', null=True)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_emprendimiento', to='gestion_creditos.credito')),
            ],
            options={
                'verbose_name': 'Detalle de Emprendimiento',
                'verbose_name_plural': 'Detalles de Emprendimiento',
            },
        ),
        migrations.CreateModel(
            name='CuentaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('INVERSIONISTA', 'Inversionista'), ('EMPRENDEDOR', 'Cliente Emprendimiento'), ('EMPLEADO', 'Cliente Libranza'), ('NATURAL', 'Persona Natural')], max_length=20)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual disponible en la cuenta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_objetivo', models.DecimalField(decimal_places=2, default=1000000, help_text='Meta de ahorro del usuario', max_digits=12)),
                ('emprendimientos_financiados', models.IntegerField(default=0, help_text='Número de emprendimientos financiados con fondos de esta cuenta')),
                ('familias_beneficiadas', models.IntegerField(default=0, help_text='Número de familias beneficiadas indirectamente')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Ahorro',
                'verbose_name_plural': 'Cuentas de Ahorro',
            },
        ),
        migrations.CreateModel(
            name='CreditoLibranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Número de cédula')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('cedula_frontal', models.FileField(upload_to='credito_libranza/cedulas/', verbose_name='Cédula (frontal)')),
                ('cedula_trasera', models.FileField(upload_to='credito_libranza/cedulas/', verbose_name='Cédula (trasera)')),
                ('certificado_laboral', models.FileField(upload_to='credito_libranza/certificados_laborales/', verbose_name='Certificado laboral')),
                ('desprendible_nomina', models.FileField(upload_to='credito_libranza/desprendibles_nomina/', verbose_name='Desprendible de nómina')),
                ('certificado_bancario', models.FileField(upload_to='credito_libranza/certificados_bancarios/', verbose_name='Certificado bancario')),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_libranza', to='gestion_creditos.credito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_creditos.empresa', verbose_name='Empresa donde labora')),
            ],
            options={
                'verbose_name': 'Detalle de Libranza',
                'verbose_name_plural': 'Detalles de Libranza',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, help_text='Razón o motivo del cambio de estado', null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion_creditos.credito')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('referencia_pago', models.CharField(max_length=100, unique=True, verbose_name='Referencia de transacción')),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('capital_abonado', models.DecimalField(blank=True, decimal_places=2, help_text='Porción del pago que abonó a capital', max_digits=10, null=True)),
                ('intereses_pagados', models.DecimalField(blank=True, decimal_places=2, help_text='Porción del pago que cubrió intereses', max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='gestion_creditos.credito')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO_ONLINE', 'Depósito Online'), ('DEPOSITO_OFFLINE', 'Consignación Offline'), ('RETIRO', 'Retiro'), ('INTERES', 'Interés Generado'), ('AJUSTE_ADMIN', 'Ajuste Administrativo')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='billetera/comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('nota_admin', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_creditos.cuentaahorro')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Ahorro',
                'verbose_name_plural': 'Movimientos de Ahorro',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CuotaAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('capital_a_pagar', models.DecimalField(decimal_places=2, help_text='Porción de la cuota que amortiza el capital', max_digits=12)),
                ('interes_a_pagar', models.DecimalField(decimal_places=2, help_text='Porción de la cuota que cubre intereses', max_digits=12)),
                ('valor_cuota', models.DecimalField(decimal_places=2, help_text='Valor total de la cuota (capital + intereses)', max_digits=12)),
                ('saldo_capital_pendiente', models.DecimalField(decimal_places=2, help_text='Saldo de capital pendiente después de pagar esta cuota', max_digits=12)),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Cuota pagada?')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se pagó la cuota')),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente pagado (puede diferir del valor_cuota)', max_digits=12, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_amortizacion', to='gestion_creditos.credito')),
            ],
            options={
                'verbose_name': 'Cuota de Amortización',
                'verbose_name_plural': 'Cuotas de Amortización',
                'ordering': ['credito', 'numero_cuota'],
                'unique_together': {('credito', 'numero_cuota')},
            },
        ),
    ]
