# Generated by Django 5.2 on 2025-11-18 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['estado'], name='idx_credito_estado'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['linea'], name='idx_credito_linea'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['estado', 'linea'], name='idx_credito_estado_linea'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['fecha_proximo_pago'], name='idx_credito_fecha_pago'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['estado', 'fecha_proximo_pago'], name='idx_credito_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['-fecha_solicitud'], name='idx_credito_fecha_sol'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['usuario', 'estado'], name='idx_credito_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['numero_credito'], name='idx_credito_numero'),
        ),
    ]
