# Generated by Django 5.2 on 2025-11-22 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0002_credito_idx_credito_estado_credito_idx_credito_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='datos_scoring_imagenes',
            field=models.JSONField(blank=True, default=dict, help_text='Datos completos del scoring de imágenes'),
        ),
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='puntaje_imagenes',
            field=models.FloatField(default=0.0, help_text='Puntaje obtenido del análisis de imágenes con IA (0-18)'),
        ),
        migrations.CreateModel(
            name='ImagenNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imágenes del negocio (JPG, PNG, WEBP)', upload_to='imagenes_negocios/%Y/%m/%d/')),
                ('tipo_imagen', models.CharField(choices=[('building_exterior', 'Exterior del Local/Edificio'), ('room_interior', 'Interior del Espacio'), ('products_display', 'Productos en Exhibición'), ('shelves_storage', 'Estantes/Almacenamiento'), ('general_business', 'Vista General del Negocio')], default='general_business', max_length=20, verbose_name='Tipo de imagen')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('credito_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_negocio', to='gestion_creditos.creditoemprendimiento')),
            ],
            options={
                'verbose_name': 'Imagen del Negocio',
                'verbose_name_plural': 'Imágenes del Negocio',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
