# Generated by Django 5.2 on 2025-12-23 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0003_creditoemprendimiento_datos_scoring_imagenes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO_APROBADO', 'Crédito Aprobado'), ('CREDITO_RECHAZADO', 'Crédito Rechazado'), ('PAGO_RECIBIDO', 'Pago Recibido'), ('PAGO_PENDIENTE', 'Pago Pendiente'), ('CONSIGNACION_APROBADA', 'Consignación Aprobada'), ('CONSIGNACION_RECHAZADA', 'Consignación Rechazada'), ('DOCUMENTO_PENDIENTE', 'Documento Pendiente'), ('MORA', 'Crédito en Mora'), ('SISTEMA', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='URL a la que redirige la notificación', max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='gestion_cre_usuario_ca11ec_idx'), models.Index(fields=['usuario', 'leida'], name='gestion_cre_usuario_290812_idx')],
            },
        ),
    ]
