# Generated by Django 5.2 on 2026-01-06 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0004_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReestructuracionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reestructuracion', models.DateTimeField(auto_now_add=True)),
                ('monto_abonado', models.DecimalField(decimal_places=2, help_text='Monto total abonado que generó la reestructuración', max_digits=10)),
                ('tipo_abono', models.CharField(choices=[('NORMAL', 'Abono Normal'), ('CAPITAL', 'Abono a Capital'), ('MAYOR', 'Abono Mayor (>2 cuotas)')], default='NORMAL', max_length=20)),
                ('plan_anterior', models.JSONField(help_text='Plan de pagos antes del abono (JSON con cuotas restantes)')),
                ('plan_nuevo', models.JSONField(help_text='Plan de pagos después del abono (JSON con cuotas recalculadas)')),
                ('saldo_pendiente_anterior', models.DecimalField(decimal_places=2, help_text='Saldo pendiente antes del abono', max_digits=12)),
                ('capital_pendiente_anterior', models.DecimalField(decimal_places=2, help_text='Capital pendiente antes del abono', max_digits=12)),
                ('plazo_restante_anterior', models.IntegerField(help_text='Cuotas restantes antes del abono')),
                ('saldo_pendiente_nuevo', models.DecimalField(decimal_places=2, help_text='Saldo pendiente después del abono', max_digits=12)),
                ('capital_pendiente_nuevo', models.DecimalField(decimal_places=2, help_text='Capital pendiente después del abono', max_digits=12)),
                ('plazo_restante_nuevo', models.IntegerField(help_text='Cuotas restantes después del abono')),
                ('ahorro_intereses', models.DecimalField(decimal_places=2, help_text='Ahorro en intereses debido a la reestructuración', max_digits=10)),
                ('cuota_mensual_nueva', models.DecimalField(blank=True, decimal_places=2, help_text='Nueva cuota mensual (si cambió)', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la reestructuración')),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Usuario que aprobó la reestructuración (puede ser el cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reestructuraciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reestructuraciones', to='gestion_creditos.credito')),
                ('pago_relacionado', models.ForeignKey(blank=True, help_text='Pago que generó esta reestructuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reestructuracion', to='gestion_creditos.historialpago')),
            ],
            options={
                'verbose_name': 'Reestructuración de Crédito',
                'verbose_name_plural': 'Reestructuraciones de Crédito',
                'ordering': ['-fecha_reestructuracion'],
                'indexes': [models.Index(fields=['credito', '-fecha_reestructuracion'], name='gestion_cre_credito_1c1f16_idx'), models.Index(fields=['tipo_abono'], name='gestion_cre_tipo_ab_f29e35_idx')],
            },
        ),
    ]
