# Generated by Django 5.2 on 2026-01-12 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0005_reestructuracioncredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapSignWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_token', models.CharField(db_index=True, help_text='Token del documento de ZapSign', max_length=100)),
                ('event', models.CharField(help_text='Tipo de evento (doc_signed, doc_viewed, etc)', max_length=50)),
                ('payload', models.JSONField(help_text='Payload completo del webhook')),
                ('headers', models.JSONField(default=dict, help_text='Headers HTTP recibidos')),
                ('signature_valid', models.BooleanField(default=False, help_text='Si la firma/secret fue validada correctamente')),
                ('processed', models.BooleanField(default=False, help_text='Si el webhook fue procesado exitosamente')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde donde vino el webhook')),
            ],
            options={
                'verbose_name': 'Log de Webhook ZapSign',
                'verbose_name_plural': 'Logs de Webhooks ZapSign',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['doc_token', '-received_at'], name='gestion_cre_doc_tok_508abc_idx'), models.Index(fields=['event', 'processed'], name='gestion_cre_event_60deed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagare', models.CharField(editable=False, help_text='Ej: PAG-2026-00123', max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('CREATED', 'Creado'), ('SENT', 'Enviado a ZapSign'), ('SIGNED', 'Firmado'), ('REFUSED', 'Rechazado por Cliente'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=20)),
                ('version_plantilla', models.CharField(default='1.0', help_text='Versión de la plantilla legal usada', max_length=10)),
                ('archivo_pdf', models.FileField(help_text='PDF original generado', upload_to='pagares/%Y/%m/')),
                ('archivo_pdf_firmado', models.FileField(blank=True, help_text='PDF firmado descargado de ZapSign', null=True, upload_to='pagares_firmados/%Y/%m/')),
                ('hash_pdf', models.CharField(blank=True, help_text='SHA-256 del PDF original (trazabilidad)', max_length=64, null=True)),
                ('zapsign_doc_token', models.CharField(blank=True, db_index=True, help_text='Token del documento en ZapSign (PRIMARY KEY de integración)', max_length=100, null=True, unique=True)),
                ('zapsign_sign_url', models.URLField(blank=True, help_text='URL de firma enviada al cliente', max_length=500, null=True)),
                ('zapsign_signed_file_url', models.URLField(blank=True, help_text='URL del PDF firmado en ZapSign', max_length=500, null=True)),
                ('zapsign_status', models.CharField(blank=True, help_text='Status reportado por ZapSign (pending, signed, refused)', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Cuándo se envió a ZapSign', null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, help_text='Timestamp de firma del cliente (from webhook)', null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, help_text='Si el cliente rechazó firmar', null=True)),
                ('ip_firmante', models.GenericIPAddressField(blank=True, help_text='IP del cliente al firmar (evidencia)', null=True)),
                ('evidencias', models.JSONField(blank=True, default=dict, help_text='Datos completos del webhook (auditoría)')),
                ('creado_por', models.ForeignKey(help_text='Usuario que generó el pagaré', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagares_creados', to=settings.AUTH_USER_MODEL)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagare', to='gestion_creditos.credito')),
            ],
            options={
                'verbose_name': 'Pagaré',
                'verbose_name_plural': 'Pagarés',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['zapsign_doc_token'], name='gestion_cre_zapsign_c914b8_idx'), models.Index(fields=['estado', 'fecha_creacion'], name='gestion_cre_estado_76522b_idx')],
            },
        ),
    ]
