# Generated by Django 5.2 on 2026-02-09 03:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0008_ingresos_mensuales_libranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion_marketplace',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('beneficio', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('publicidad', 'Publicidad')], max_length=20)),
                ('precio', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marketplace/items/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('whatsapp_contacto', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to='gestion_creditos.empresa')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
