# Generated by Django 5.2 on 2026-02-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _crear_historial_inicial(apps, schema_editor):
    MarketplaceItem = apps.get_model('gestion_creditos', 'MarketplaceItem')
    Historial = apps.get_model('gestion_creditos', 'MarketplaceItemHistorialEstado')

    historial_actual = set(
        Historial.objects.values_list('item_id', flat=True).distinct()
    )

    nuevos = []
    for item in MarketplaceItem.objects.all().iterator():
        if item.id in historial_actual:
            continue
        nuevos.append(
            Historial(
                item_id=item.id,
                estado_anterior='',
                estado_nuevo=item.estado,
                origen='sistema',
                comentario='Estado inicial migrado.'
            )
        )
    if nuevos:
        Historial.objects.bulk_create(nuevos, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0009_empresa_descripcion_marketplace_empresa_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItemHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], max_length=20)),
                ('origen', models.CharField(choices=[('empresa', 'Empresa'), ('admin', 'Administrador'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion_creditos.marketplaceitem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_cambios_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado marketplace',
                'verbose_name_plural': 'Historial de estados marketplace',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceitemhistorialestado',
            index=models.Index(fields=['item', '-fecha_cambio'], name='mk_hist_item_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceitemhistorialestado',
            index=models.Index(fields=['item', 'estado_nuevo'], name='mk_hist_item_estado_idx'),
        ),
        migrations.RunPython(
            code=_crear_historial_inicial,
            reverse_code=migrations.RunPython.noop
        ),
    ]
