# Generated by Django 5.2 on 2026-02-16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0010_marketplaceitemhistorialestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='video',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='marketplace/videos/',
                validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])
                ],
            ),
        ),
    ]
