# Generated by Django 5.2 on 2026-02-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0011_marketplaceitem_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoahorro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente Aprobacion'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoahorro',
            name='tipo',
            field=models.CharField(choices=[('DEPOSITO_ONLINE', 'Deposito Online'), ('DEPOSITO_OFFLINE', 'Consignacion Offline'), ('RETIRO', 'Retiro'), ('INTERES', 'Interes Generado'), ('AJUSTE_ADMIN', 'Ajuste Administrativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('CREDITO_APROBADO', 'Credito Aprobado'), ('CREDITO_RECHAZADO', 'Credito Rechazado'), ('PAGO_RECIBIDO', 'Pago Recibido'), ('PAGO_PENDIENTE', 'Pago Pendiente'), ('CONSIGNACION_APROBADA', 'Consignacion Aprobada'), ('CONSIGNACION_RECHAZADA', 'Consignacion Rechazada'), ('DOCUMENTO_PENDIENTE', 'Documento Pendiente'), ('MORA', 'Credito en Mora'), ('SISTEMA', 'Notificacion del Sistema')], max_length=30),
        ),
    ]
