# Generated by Django 5.2 on 2026-03-25 05:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0019_empresa_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('CONVENIO', 'Convenio'), ('MARKETPLACE_EXTERNA', 'Marketplace externa'), ('MIXTA', 'Mixta')], default='CONVENIO', max_length=24),
        ),
        migrations.AddField(
            model_name='vinculolaboralempresa',
            name='auxilio_transporte_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vinculolaboralempresa',
            name='cargado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vinculolaboralempresa',
            name='descuentos_fijos_mensuales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vinculolaboralempresa',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=10),
        ),
    ]
