# Generated by Django 5.2 on 2026-03-31 17:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0020_empresa_tipo_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpago',
            options={'ordering': ['-fecha_aplicacion', '-fecha_pago'], 'verbose_name': 'Historial de Pago', 'verbose_name_plural': 'Historial de Pagos'},
        ),
        migrations.AddField(
            model_name='historialpago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='creditos/pagos/comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='empresa_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_credito_registrados', to='gestion_creditos.empresa'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aplicacion'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='metodo_pago',
            field=models.CharField(choices=[('NO_DEFINIDO', 'No definido'), ('WOMPI', 'Wompi'), ('TRANSFERENCIA_DIRECTA', 'Transferencia directa'), ('OFFLINE_MANUAL', 'Offline manual')], default='NO_DEFINIDO', max_length=30),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='origen_registro',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('PASARELA_WOMPI', 'Pasarela Wompi'), ('CARGA_MASIVA_EMPRESA', 'Carga masiva empresa'), ('REGISTRO_MANUAL_ADMIN', 'Registro manual admin'), ('REGISTRO_MANUAL_PAGADOR', 'Registro manual pagador')], default='LEGACY', max_length=32),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_credito_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='wompi_intento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_historial', to='gestion_creditos.wompiintent'),
        ),
        migrations.CreateModel(
            name='LotePagoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='creditos/pagos/lotes/%Y/%m/')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='creditos/pagos/comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('CARGADO', 'Cargado'), ('PROCESADO', 'Procesado'), ('PROCESADO_CON_ERRORES', 'Procesado con errores')], default='CARGADO', max_length=32)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('pagos_aplicados', models.PositiveIntegerField(default=0)),
                ('errores_count', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_pago', to='gestion_creditos.empresa')),
            ],
            options={
                'verbose_name': 'Lote de pago de empresa',
                'verbose_name_plural': 'Lotes de pago de empresas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='historialpago',
            name='lote_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='gestion_creditos.lotepagoempresa'),
        ),
        migrations.AddIndex(
            model_name='lotepagoempresa',
            index=models.Index(fields=['empresa', 'checksum'], name='lote_pago_emp_chk_idx'),
        ),
    ]
