# Generated by Django 5.2 on 2026-04-19 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0022_cuotaamortizacion_notificacion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleContablePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia_aplicacion', models.PositiveIntegerField(default=1)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Porcion del pago aplicada al capital financiado de la cuota.', max_digits=12)),
                ('interes_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Porcion del pago aplicada a intereses de la cuota.', max_digits=12)),
                ('capital_principal_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Porcion del capital aplicado atribuida al monto aprobado original.', max_digits=12)),
                ('comision_aplicada', models.DecimalField(decimal_places=2, default=0, help_text='Porcion del capital aplicado atribuida a la comision financiada.', max_digits=12)),
                ('iva_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Porcion del capital aplicado atribuida al IVA financiado.', max_digits=12)),
                ('metodologia_calculo', models.CharField(choices=[('CUOTA_INTERES_PRIMERO', 'Interes primero sobre cuota')], default='CUOTA_INTERES_PRIMERO', help_text='Metodo usado para desglosar contablemente la aplicacion del pago.', max_length=32)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_contables_pago', to='gestion_creditos.credito')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_contables_pago', to='gestion_creditos.cuotaamortizacion')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_contables', to='gestion_creditos.historialpago')),
            ],
            options={
                'verbose_name': 'Detalle contable de pago',
                'verbose_name_plural': 'Detalles contables de pago',
                'ordering': ['pago', 'secuencia_aplicacion', 'id'],
                'indexes': [models.Index(fields=['pago', 'secuencia_aplicacion'], name='idx_detcont_pago_seq'), models.Index(fields=['credito', 'fecha_aplicacion'], name='idx_detcont_cred_fecha')],
            },
        ),
    ]
