# Generated by Django 5.2 on 2026-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0027_merge_landing_logo_into_logo_and_remove_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesorcomercial',
            options={'ordering': ['nombre'], 'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivos'},
        ),
        migrations.AlterField(
            model_name='detallecontablepago',
            name='metodologia_calculo',
            field=models.CharField(choices=[('CUOTA_INTERES_PRIMERO', 'Interes primero sobre cuota'), ('ABONO_CAPITAL_DIRECTO', 'Abono directo a capital')], default='CUOTA_INTERES_PRIMERO', help_text='Metodo usado para desglosar contablemente la aplicacion del pago.', max_length=32),
        ),
    ]
