# Generated by Django 5.2 on 2026-05-09 03:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0028_alter_asesorcomercial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComisionEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comisiones_ejecutivos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comision', to='gestion_creditos.asesorcomercial')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_comision_ejecutivo_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de comision de ejecutivo',
                'verbose_name_plural': 'Pagos de comision de ejecutivos',
                'ordering': ['-fecha_pago', '-creado_en'],
                'indexes': [models.Index(fields=['asesor', '-fecha_pago'], name='pago_com_eje_asesor_fecha_idx')],
            },
        ),
    ]
