# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0030_pagocomisionejecutivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoReglaEspecialAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('monthly_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_total_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('simulation_payload', models.JSONField(blank=True, default=dict)),
                ('business_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_especiales_libranza_creadas', to=settings.AUTH_USER_MODEL)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_especiales_audit', to='gestion_creditos.credito')),
            ],
            options={
                'verbose_name': 'Auditoria regla especial libranza',
                'verbose_name_plural': 'Auditorias reglas especiales libranza',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['-created_at'], name='special_audit_created_idx'),
                    models.Index(fields=['credito', '-created_at'], name='special_audit_credit_idx'),
                ],
            },
        ),
    ]
