# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0031_creditoreglaspecialaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión de estudio del crédito', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='iva_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA sobre la comisión (19%)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto aprobado por el analista (puede diferir del solicitado)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, help_text='Monto solicitado por el cliente', max_digits=14),
        ),
        migrations.AlterField(
            model_name='credito',
            name='valor_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de la cuota fija mensual', max_digits=14, null=True),
        ),
    ]
