# Generated by Django 5.2 on 2026-05-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0032_expand_credit_special_case_money_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('can_originate_special_libranza', 'Puede simular y originar casos especiales de libranza')], 'verbose_name': 'Crédito', 'verbose_name_plural': 'Créditos'},
        ),
    ]
