# Generated by Django 5.2 on 2026-05-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0033_add_special_libranza_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('can_originate_special_libranza', 'Puede simular y originar casos especiales de libranza'), ('can_run_risk_diagnostic', 'Puede ejecutar diagnosticos internos de riesgo')], 'verbose_name': 'Crédito', 'verbose_name_plural': 'Créditos'},
        ),
    ]
