# Generated by Django 5.2 on 2025-11-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('estimacion', models.IntegerField()),
            ],
        ),
    ]
