# Generated by Django 5.2 on 2026-07-24 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=160)),
                ('apellidos', models.CharField(max_length=160)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria'), ('RC', 'Registro civil'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento_confirmada', models.BooleanField(default=False)),
                ('responsable_contractual', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_financiacion_educativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de financiacion',
                'verbose_name_plural': 'Participantes de financiacion',
                'ordering': ['solicitud', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudFinanciacionEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=160)),
                ('apellidos', models.CharField(max_length=160)),
                ('celular', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('valor_plan', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plazo_meses', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nombre_curso', models.CharField(max_length=200)),
                ('tipo_curso', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING_USER_REGISTRATION', max_length=40)),
                ('canal_origen', models.CharField(default='INSTITUTION_API', max_length=40)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_origen', models.CharField(blank=True, max_length=512)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_financiacion_educativa', to='instituciones.institucion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_financiacion_educativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de financiacion educativa',
                'verbose_name_plural': 'Solicitudes de financiacion educativa',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='RolParticipanteFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('STUDENT', 'Estudiante'), ('GUARDIAN', 'Tutor'), ('PRINCIPAL_DEBTOR', 'Deudor principal')], max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='financiacion_educativa.participantefinanciacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_participantes', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Rol de participante',
                'verbose_name_plural': 'Roles de participantes',
                'ordering': ['solicitud', 'rol'],
            },
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='financiacion_educativa.solicitudfinanciacioneducativa'),
        ),
        migrations.CreateModel(
            name='HistorialEstadoSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40, null=True)),
                ('estado_nuevo', models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40)),
                ('motivo', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_financiacion_educativa', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Historial de estado de solicitud',
                'verbose_name_plural': 'Historiales de estados de solicitudes',
                'ordering': ['creado_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentoFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('STUDENT_ID_FRONT', 'Documento frontal del estudiante'), ('GUARDIAN_ID_FRONT', 'Documento frontal del tutor'), ('OTHER', 'Otro')], max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='financiacion_educativa/documentos/%Y/%m/')),
                ('referencia_almacenamiento', models.CharField(blank=True, max_length=500)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamano_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('estado_validacion', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('origen_captura', models.CharField(choices=[('INSTITUTION_API', 'API institucional'), ('USER_UPLOAD', 'Carga del usuario'), ('CAMERA', 'Camara'), ('INTERNAL', 'Generado internamente')], max_length=30)),
                ('sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('resultado_procesamiento', models.JSONField(blank=True, default=dict)),
                ('nivel_confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='financiacion_educativa.participantefinanciacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Documento de financiacion',
                'verbose_name_plural': 'Documentos de financiacion',
                'ordering': ['-cargado_en'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TERMS', 'Terminos y condiciones'), ('DATA_PROCESSING', 'Tratamiento de datos'), ('CREDIT_AUTHORIZATION', 'Autorizacion de financiacion')], max_length=40)),
                ('version_texto', models.CharField(max_length=40)),
                ('aceptado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('evidencia_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_financiacion_educativa', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='financiacion_educativa.participantefinanciacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-aceptado_en'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CondicionesFinancieras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_financiado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_meses', models.PositiveSmallIntegerField()),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tasa_comision', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_iva_comision', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor_iva_comision', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_financiado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_cuota_estimada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes_total_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_calculo', models.CharField(choices=[('FRENCH_AMORTIZATION', 'Anualidad francesa')], max_length=40)),
                ('base_calculo', models.JSONField(default=dict)),
                ('version_regla', models.CharField(max_length=60)),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_primer_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_vencimiento', models.DateField(blank=True, null=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='condiciones_financieras', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Condiciones financieras',
                'verbose_name_plural': 'Condiciones financieras',
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='solicitudfinanciacioneducativa',
            index=models.Index(fields=['institucion', 'estado'], name='sol_edu_inst_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfinanciacioneducativa',
            index=models.Index(fields=['correo'], name='sol_edu_correo_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfinanciacioneducativa',
            index=models.Index(fields=['creada_en'], name='sol_edu_creada_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudfinanciacioneducativa',
            constraint=models.UniqueConstraint(fields=('institucion', 'referencia_externa'), name='uniq_solicitud_ref_institucion'),
        ),
        migrations.AddConstraint(
            model_name='rolparticipantefinanciacion',
            constraint=models.UniqueConstraint(fields=('participante', 'rol'), name='uniq_rol_por_participante'),
        ),
        migrations.AddConstraint(
            model_name='rolparticipantefinanciacion',
            constraint=models.UniqueConstraint(fields=('solicitud', 'rol'), name='uniq_rol_por_solicitud'),
        ),
        migrations.AddIndex(
            model_name='participantefinanciacion',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='part_edu_documento_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantefinanciacion',
            constraint=models.UniqueConstraint(fields=('solicitud', 'tipo_documento', 'numero_documento'), name='uniq_participante_doc_solicitud'),
        ),
        migrations.AddIndex(
            model_name='historialestadosolicitud',
            index=models.Index(fields=['solicitud', 'creado_en'], name='hist_edu_sol_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofinanciacion',
            index=models.Index(fields=['solicitud', 'tipo'], name='doc_edu_sol_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofinanciacion',
            index=models.Index(fields=['estado_validacion'], name='doc_edu_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentofinanciacion',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('solicitud', 'sha256'), name='uniq_documento_hash_solicitud'),
        ),
        migrations.AddConstraint(
            model_name='consentimiento',
            constraint=models.CheckConstraint(condition=models.Q(('participante__isnull', False), ('usuario__isnull', False), _connector='OR'), name='consentimiento_aceptante_requerido'),
        ),
        migrations.AddConstraint(
            model_name='consentimiento',
            constraint=models.UniqueConstraint(fields=('solicitud', 'participante', 'tipo', 'version_texto'), name='uniq_consent_part_tipo_version'),
        ),
    ]
