# Generated by Django 5.2 on 2026-07-24 04:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0001_initial'),
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIdempotenciaSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_reuso_en', models.DateTimeField(blank=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_idempotencia_financiacion', to='instituciones.institucion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_idempotencia', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Registro de idempotencia de solicitud',
                'verbose_name_plural': 'Registros de idempotencia de solicitudes',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['institucion', 'creada_en'], name='idem_edu_inst_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'clave_hash'), name='uniq_idempotencia_clave_institucion')],
            },
        ),
    ]
