# Generated by Django 5.2 on 2026-07-24 04:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0002_registroidempotenciasolicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoInvitacionContinuacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ISSUED', 'Emitida'), ('REVOKED', 'Revocada'), ('CONSUMED', 'Consumida')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Evento de invitacion',
                'verbose_name_plural': 'Eventos de invitaciones',
                'ordering': ['creado_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvitacionContinuacionSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('proposito', models.CharField(choices=[('CONTINUE_APPLICATION', 'Continuar solicitud')], default='CONTINUE_APPLICATION', max_length=40)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('CONSUMED', 'Consumida'), ('REVOKED', 'Revocada')], default='ACTIVE', max_length=20)),
                ('vence_en', models.DateTimeField()),
                ('consumida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitacion de continuacion',
                'verbose_name_plural': 'Invitaciones de continuacion',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='VersionTerminosFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TERMS', 'Terminos y condiciones'), ('DATA_PROCESSING', 'Tratamiento de datos'), ('CREDIT_AUTHORIZATION', 'Autorizacion de financiacion')], max_length=40)),
                ('version', models.CharField(max_length=40, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('hash_integridad', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('obligatorio', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('RETIRED', 'Retirada')], default='DRAFT', max_length=20)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('vigente_desde', models.DateTimeField(blank=True, null=True)),
                ('retirada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version de terminos de financiacion',
                'verbose_name_plural': 'Versiones de terminos de financiacion',
                'ordering': ['tipo', '-vigente_desde', '-creada_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='consentimiento',
            name='uniq_consent_part_tipo_version',
        ),
        migrations.AddConstraint(
            model_name='consentimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('participante__isnull', False)), fields=('solicitud', 'participante', 'tipo', 'version_texto'), name='uniq_consent_part_tipo_version'),
        ),
        migrations.AddConstraint(
            model_name='consentimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('solicitud', 'usuario', 'tipo', 'version_texto'), name='uniq_consent_user_tipo_version'),
        ),
        migrations.AddField(
            model_name='eventoinvitacioncontinuacion',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_invitacion_educativa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacioncontinuacionsolicitud',
            name='consumida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_educativas_consumidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacioncontinuacionsolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_continuacion', to='financiacion_educativa.solicitudfinanciacioneducativa'),
        ),
        migrations.AddField(
            model_name='eventoinvitacioncontinuacion',
            name='invitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='financiacion_educativa.invitacioncontinuacionsolicitud'),
        ),
        migrations.AddIndex(
            model_name='versionterminosfinanciacion',
            index=models.Index(fields=['estado', 'vigente_desde'], name='term_edu_estado_vig_idx'),
        ),
        migrations.AddIndex(
            model_name='versionterminosfinanciacion',
            index=models.Index(fields=['tipo', 'obligatorio'], name='term_edu_tipo_obl_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacioncontinuacionsolicitud',
            index=models.Index(fields=['solicitud', 'estado'], name='inv_edu_sol_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacioncontinuacionsolicitud',
            index=models.Index(fields=['vence_en'], name='inv_edu_vence_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitacioncontinuacionsolicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVE')), fields=('solicitud',), name='uniq_invitacion_activa_solicitud'),
        ),
        migrations.AddConstraint(
            model_name='invitacioncontinuacionsolicitud',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumida_en__isnull', False), ('consumida_por__isnull', False), ('estado', 'CONSUMED')), models.Q(('estado', 'CONSUMED'), _negated=True), _connector='OR'), name='invitacion_consumida_con_auditoria'),
        ),
        migrations.AddIndex(
            model_name='eventoinvitacioncontinuacion',
            index=models.Index(fields=['invitacion', 'creado_en'], name='evt_inv_edu_fecha_idx'),
        ),
    ]
