# Generated by Django 5.2 on 2026-07-25 04:06

import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import financiacion_educativa.storage
import uuid
from django.conf import settings
from django.db import migrations, models


def desactivar_documentos_duplicados(apps, schema_editor):
    Documento = apps.get_model('financiacion_educativa', 'DocumentoFinanciacion')
    grupos = (
        Documento.objects.values('solicitud_id', 'participante_id', 'tipo')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    for grupo in grupos.iterator():
        documentos = Documento.objects.filter(
            solicitud_id=grupo['solicitud_id'],
            participante_id=grupo['participante_id'],
            tipo=grupo['tipo'],
        ).order_by('-cargado_en', '-id')
        vigente = documentos.values_list('id', flat=True).first()
        documentos.exclude(id=vigente).update(activo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0003_eventoinvitacioncontinuacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoParticipanteFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado')], max_length=20)),
                ('campos_modificados', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Evento de participante',
                'verbose_name_plural': 'Eventos de participantes',
                'ordering': ['creado_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EvidenciaMatricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institucion_declarada', models.CharField(max_length=200)),
                ('programa_curso', models.CharField(max_length=200)),
                ('periodo_academico', models.CharField(max_length=80)),
                ('referencia_matricula', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente de revision'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, choices=[('UNREADABLE', 'Documento ilegible'), ('INCOMPLETE', 'Documento incompleto'), ('WRONG_DOCUMENT', 'Tipo documental incorrecto'), ('EXPIRED', 'Documento vencido'), ('DATA_MISMATCH', 'Datos no coinciden'), ('OTHER', 'Otro motivo controlado')], max_length=30)),
                ('observacion_revision', models.CharField(blank=True, max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evidencia de matricula',
                'verbose_name_plural': 'Evidencias de matricula',
            },
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='cargado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_financiacion_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='escaneado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='estado_escaneo',
            field=models.CharField(choices=[('PENDING_SECURITY_SCAN', 'Pendiente de escaneo de seguridad'), ('SAFE', 'Sin hallazgos reportados por el escaner'), ('BLOCKED', 'Bloqueado por seguridad')], default='PENDING_SECURITY_SCAN', max_length=30),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('UNREADABLE', 'Documento ilegible'), ('INCOMPLETE', 'Documento incompleto'), ('WRONG_DOCUMENT', 'Tipo documental incorrecto'), ('EXPIRED', 'Documento vencido'), ('DATA_MISMATCH', 'Datos no coinciden'), ('OTHER', 'Otro motivo controlado')], max_length=30),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='nombre_seguro',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='observacion_revision',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='reemplaza_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos', to='financiacion_educativa.documentofinanciacion'),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='referencia_escaneo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_financiacion_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_financiacion_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_financiacion_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='identidad_verificada',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='pais_expedicion',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='relacion_estudiante',
            field=models.CharField(blank=True, choices=[('SELF', 'La misma persona'), ('MOTHER', 'Madre'), ('FATHER', 'Padre'), ('LEGAL_GUARDIAN', 'Representante legal declarado'), ('FAMILY_MEMBER', 'Familiar'), ('OTHER', 'Otra relacion declarada')], max_length=30),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='relacion_verificada',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='participantefinanciacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='rolparticipantefinanciacion',
            name='declarado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_financiacion_declarados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=financiacion_educativa.storage.private_document_storage, upload_to=financiacion_educativa.models.ruta_documento_privado),
        ),
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDING', 'Pendiente de revision'), ('APPROVED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='tipo',
            field=models.CharField(choices=[('STUDENT_IDENTIFICATION', 'Identificacion del estudiante'), ('GUARDIAN_IDENTIFICATION', 'Identificacion del tutor'), ('DEBTOR_IDENTIFICATION', 'Identificacion del posible deudor'), ('ENROLLMENT_EVIDENCE', 'Evidencia de matricula'), ('OTHER_EDUCATIONAL', 'Otro documento educativo'), ('STUDENT_ID_FRONT', 'Identificacion del estudiante (anterior)'), ('GUARDIAN_ID_FRONT', 'Identificacion del tutor (anterior)'), ('OTHER', 'Otro documento (anterior)')], max_length=50),
        ),
        migrations.RunPython(
            desactivar_documentos_duplicados,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='documentofinanciacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('participante__isnull', False)), fields=('solicitud', 'participante', 'tipo'), name='uniq_doc_activo_part_tipo'),
        ),
        migrations.AddConstraint(
            model_name='documentofinanciacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('participante__isnull', True)), fields=('solicitud', 'tipo'), name='uniq_doc_activo_sol_tipo'),
        ),
        migrations.AddField(
            model_name='eventoparticipantefinanciacion',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_participantes_financiacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoparticipantefinanciacion',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='financiacion_educativa.participantefinanciacion'),
        ),
        migrations.AddField(
            model_name='evidenciamatricula',
            name='documento_soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_matricula', to='financiacion_educativa.documentofinanciacion'),
        ),
        migrations.AddField(
            model_name='evidenciamatricula',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_matricula_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciamatricula',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_matricula_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciamatricula',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidencia_matricula', to='financiacion_educativa.solicitudfinanciacioneducativa'),
        ),
    ]
