# Generated by Django 5.2 on 2026-07-25 16:33

import django.core.validators
import django.db.models.deletion
import financiacion_educativa.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def preservar_fotografias_anteriores(apps, schema_editor):
    Condiciones = apps.get_model(
        'financiacion_educativa',
        'CondicionesFinancieras',
    )
    Condiciones.objects.all().update(
        es_legado=True,
        activa=False,
        bloqueada=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0004_eventoparticipantefinanciacion_evidenciamatricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaAmortizacionEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Cuota de amortizacion educativa',
                'verbose_name_plural': 'Cuotas de amortizacion educativa',
                'ordering': ['fotografia', 'numero'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='condicionesfinancieras',
            options={'ordering': ['solicitud', '-numero_version'], 'verbose_name': 'Condiciones financieras', 'verbose_name_plural': 'Condiciones financieras'},
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fotografias_financieras_educativas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='es_legado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            preservar_fotografias_anteriores,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='huella_determinantes',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')]),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='numero_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='politica_causacion',
            field=models.CharField(choices=[('DAILY_30', 'Prorrateo diario, base comercial de 30 dias')], default='DAILY_30', max_length=30),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='politica_redondeo',
            field=models.CharField(choices=[('COP_PESO_HALF_UP', 'COP al peso, mitad hacia arriba')], default='COP_PESO_HALF_UP', max_length=40),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='proveedor_fondo_garantias',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='proveedor_seguro_vida',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='tasa_fondo_garantias',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='tasa_seguro_vida',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='valor_fondo_garantias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='valor_seguro_vida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='condicionesfinancieras',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotografias_financieras', to='financiacion_educativa.solicitudfinanciacioneducativa'),
        ),
        migrations.CreateModel(
            name='ConfiguracionFinancieraEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60)),
                ('version', models.PositiveIntegerField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activa'), ('RETIRED', 'Retirada')], default='DRAFT', max_length=20)),
                ('porcentaje_originacion', models.DecimalField(decimal_places=6, max_digits=9)),
                ('porcentaje_iva_originacion', models.DecimalField(decimal_places=6, max_digits=9)),
                ('porcentaje_fondo_garantias', models.DecimalField(decimal_places=6, max_digits=9)),
                ('proveedor_fondo_garantias', models.CharField(max_length=120)),
                ('porcentaje_seguro_vida', models.DecimalField(decimal_places=6, max_digits=9)),
                ('proveedor_seguro_vida', models.CharField(max_length=120)),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=6, max_digits=9)),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('metodo_calculo', models.CharField(choices=[('FRENCH_AMORTIZATION', 'Anualidad francesa')], default='FRENCH_AMORTIZATION', max_length=40)),
                ('politica_redondeo', models.CharField(choices=[('COP_PESO_HALF_UP', 'COP al peso, mitad hacia arriba')], default='COP_PESO_HALF_UP', max_length=40)),
                ('politica_causacion', models.CharField(choices=[('DAILY_30', 'Prorrateo diario, base comercial de 30 dias')], default='DAILY_30', max_length=30)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_financieras_educativas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_financieras_educativas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion financiera educativa',
                'verbose_name_plural': 'Configuraciones financieras educativas',
                'ordering': ['codigo', '-version'],
            },
        ),
        migrations.AddField(
            model_name='condicionesfinancieras',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fotografias', to='financiacion_educativa.configuracionfinancieraeducativa'),
        ),
        migrations.AddIndex(
            model_name='condicionesfinancieras',
            index=models.Index(fields=['solicitud', 'activa'], name='foto_fin_edu_activa_idx'),
        ),
        migrations.AddConstraint(
            model_name='condicionesfinancieras',
            constraint=models.UniqueConstraint(fields=('solicitud', 'numero_version'), name='uniq_foto_fin_edu_version'),
        ),
        migrations.AddConstraint(
            model_name='condicionesfinancieras',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('solicitud',), name='uniq_foto_fin_edu_activa'),
        ),
        migrations.AddField(
            model_name='cuotaamortizacioneducativa',
            name='fotografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='financiacion_educativa.condicionesfinancieras'),
        ),
        migrations.AddIndex(
            model_name='configuracionfinancieraeducativa',
            index=models.Index(fields=['estado', 'vigente_desde', 'vigente_hasta'], name='cfg_fin_edu_vigencia_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionfinancieraeducativa',
            constraint=models.UniqueConstraint(fields=('codigo', 'version'), name='uniq_config_fin_edu_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='cuotaamortizacioneducativa',
            constraint=models.UniqueConstraint(fields=('fotografia', 'numero'), name='uniq_cuota_fin_edu_numero'),
        ),
    ]
