# Generated by Django 5.2 on 2026-07-25 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0005_cuotaamortizacioneducativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoinvitacioncontinuacion',
            name='tipo',
            field=models.CharField(choices=[('ISSUED', 'Emitida'), ('REVOKED', 'Revocada'), ('CONSUMED', 'Consumida'), ('DELIVERY_SCHEDULED', 'Entrega programada'), ('DELIVERY_STARTED', 'Entrega iniciada'), ('DELIVERY_SENT', 'Entrega enviada'), ('DELIVERY_FAILED', 'Entrega fallida')], max_length=20),
        ),
        migrations.CreateModel(
            name='EntregaInvitacionContinuacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secuencia', models.PositiveIntegerField()),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo electronico')], default='EMAIL', max_length=20)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'En envio'), ('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada'), ('SUPERSEDED', 'Reemplazada')], default='PENDING', max_length=20)),
                ('origen', models.CharField(choices=[('INITIAL', 'Inicial'), ('AUTOMATIC_RETRY', 'Reintento automatico'), ('MANUAL_REISSUE', 'Reemision manual')], max_length=30)),
                ('destinatario_hmac', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('codigo_ultimo_error', models.CharField(blank=True, max_length=60)),
                ('programada_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('iniciada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fallida_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_invitacion_educativa_creadas', to=settings.AUTH_USER_MODEL)),
                ('invitacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='financiacion_educativa.invitacioncontinuacionsolicitud')),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos', to='financiacion_educativa.entregainvitacioncontinuacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_invitacion', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Entrega de invitacion de continuacion',
                'verbose_name_plural': 'Entregas de invitaciones de continuacion',
                'ordering': ['solicitud', '-secuencia'],
                'indexes': [models.Index(fields=['estado', 'programada_en'], name='ent_inv_edu_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'secuencia'), name='uniq_entrega_inv_edu_secuencia'), models.UniqueConstraint(condition=models.Q(('origen', 'INITIAL')), fields=('solicitud',), name='uniq_entrega_inv_edu_inicial'), models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDING', 'SENDING'])), fields=('solicitud',), name='uniq_entrega_inv_edu_en_curso')],
            },
        ),
    ]
