# Generated by Django 5.2 on 2026-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0006_alter_eventoinvitacioncontinuacion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='codigo_matricula',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='fecha_matricula',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='fecha_nacimiento_estudiante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='jornada',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='numero_documento_estudiante',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='periodo_academico',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='sede',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='solicitudfinanciacioneducativa',
            name='tipo_documento_estudiante',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria'), ('RC', 'Registro civil'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='solicitudfinanciacioneducativa',
            index=models.Index(fields=['tipo_documento_estudiante', 'numero_documento_estudiante'], name='sol_edu_doc_est_idx'),
        ),
    ]
