# Generated by Django 5.2 on 2026-07-29 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0007_solicitudfinanciacioneducativa_codigo_matricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='tipo',
            field=models.CharField(choices=[('STUDENT_IDENTIFICATION', 'Identificacion del estudiante'), ('GUARDIAN_IDENTIFICATION', 'Identificacion del tutor'), ('DEBTOR_IDENTIFICATION', 'Identificacion del posible deudor'), ('INCOME_CERTIFICATE', 'Certificado de ingresos'), ('ENROLLMENT_EVIDENCE', 'Evidencia de matricula'), ('OTHER_EDUCATIONAL', 'Otro documento educativo'), ('STUDENT_ID_FRONT', 'Identificacion del estudiante - frente'), ('STUDENT_ID_BACK', 'Identificacion del estudiante - reverso'), ('GUARDIAN_ID_FRONT', 'Identificacion del tutor - frente'), ('GUARDIAN_ID_BACK', 'Identificacion del tutor - reverso'), ('OTHER', 'Otro documento (anterior)')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='documentofinanciacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ('STUDENT_ID_FRONT', 'STUDENT_ID_BACK', 'GUARDIAN_ID_FRONT', 'GUARDIAN_ID_BACK')), _negated=True), ('origen_captura', 'CAMERA'), _connector='OR'), name='doc_identidad_origen_camara'),
        ),
    ]
