# Generated by Django 5.2 on 2026-07-29 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0008_alter_documentofinanciacion_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCapturaMovil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona', models.CharField(choices=[('STUDENT', 'Estudiante'), ('GUARDIAN', 'Tutor')], max_length=20)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('destinatario_hmac', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activo'), ('CONSUMED', 'Consumido'), ('REVOKED', 'Revocado')], default='ACTIVE', max_length=20)),
                ('estado_entrega', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'En envio'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='PENDING', max_length=20)),
                ('vence_en', models.DateTimeField()),
                ('intentos_entrega', models.PositiveSmallIntegerField(default=0)),
                ('codigo_ultimo_error', models.CharField(blank=True, max_length=60)),
                ('entrega_iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('fallida_en', models.DateTimeField(blank=True, null=True)),
                ('revocada_en', models.DateTimeField(blank=True, null=True)),
                ('consumida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('consumida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_captura_movil_consumidos', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_captura_movil_creados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_captura_movil', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Enlace de captura movil',
                'verbose_name_plural': 'Enlaces de captura movil',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoEnlaceCapturaMovil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ISSUED', 'Emitido'), ('REVOKED', 'Revocado'), ('DELIVERY_STARTED', 'Entrega iniciada'), ('DELIVERY_SENT', 'Entrega enviada'), ('DELIVERY_FAILED', 'Entrega fallida'), ('CONSUMED', 'Consumido')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_enlace_captura_movil', to=settings.AUTH_USER_MODEL)),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='financiacion_educativa.enlacecapturamovil')),
            ],
            options={
                'verbose_name': 'Evento de enlace de captura movil',
                'verbose_name_plural': 'Eventos de enlaces de captura movil',
                'ordering': ['creado_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='enlacecapturamovil',
            index=models.Index(fields=['solicitud', 'estado'], name='enl_cap_sol_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='enlacecapturamovil',
            index=models.Index(fields=['vence_en'], name='enl_cap_vence_idx'),
        ),
        migrations.AddConstraint(
            model_name='enlacecapturamovil',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVE')), fields=('solicitud',), name='uniq_enlace_captura_activo_sol'),
        ),
        migrations.AddConstraint(
            model_name='enlacecapturamovil',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumida_en__isnull', False), ('consumida_por__isnull', False), ('estado', 'CONSUMED')), models.Q(('estado', 'CONSUMED'), _negated=True), _connector='OR'), name='enlace_captura_consumido_audit'),
        ),
        migrations.AddIndex(
            model_name='eventoenlacecapturamovil',
            index=models.Index(fields=['enlace', 'creado_en'], name='evt_enl_cap_fecha_idx'),
        ),
    ]
