# Generated by Django 5.2 on 2026-07-30 05:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0009_enlacecapturamovil_eventoenlacecapturamovil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudfinanciacioneducativa',
            options={'ordering': ['-creada_en'], 'permissions': [('revisar_solicitud_financiacion', 'Puede revisar y decidir solicitudes educativas')], 'verbose_name': 'Solicitud de financiacion educativa', 'verbose_name_plural': 'Solicitudes de financiacion educativa'},
        ),
        migrations.AlterField(
            model_name='historialestadosolicitud',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('APPROVED', 'Aprobada; curso autorizado'), ('REJECTED', 'Rechazada'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadosolicitud',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('APPROVED', 'Aprobada; curso autorizado'), ('REJECTED', 'Rechazada'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitudfinanciacioneducativa',
            name='estado',
            field=models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('APPROVED', 'Aprobada; curso autorizado'), ('REJECTED', 'Rechazada'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING_USER_REGISTRATION', max_length=40),
        ),
        migrations.CreateModel(
            name='DecisionRevisionEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('APPROVED', 'Aprobar y autorizar curso'), ('REJECTED', 'Rechazar'), ('CORRECTION_REQUESTED', 'Solicitar correcciones')], max_length=30)),
                ('motivo', models.CharField(choices=[('REQUIREMENTS_VERIFIED', 'Requisitos verificados'), ('INCOMPLETE_INFORMATION', 'Informacion incompleta'), ('UNREADABLE_DOCUMENT', 'Documento ilegible'), ('IDENTITY_MISMATCH', 'Inconsistencia de identidad'), ('GUARDIANSHIP_NOT_VERIFIED', 'Representacion no verificada'), ('ENROLLMENT_NOT_VERIFIED', 'Matricula no verificada'), ('OTHER', 'Otro motivo controlado')], max_length=40)),
                ('mensaje_solicitante', models.CharField(blank=True, max_length=500)),
                ('observacion_interna', models.CharField(blank=True, max_length=1000)),
                ('requisitos_pendientes', models.JSONField(blank=True, default=list)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fotografia_financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_revision', to='financiacion_educativa.condicionesfinancieras')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_revision_educativa', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_revision', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Decision de revision educativa',
                'verbose_name_plural': 'Decisiones de revision educativa',
                'ordering': ['-creada_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntregaCorreoEstadoSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'En envio'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('destinatario_hmac', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('codigo_ultimo_error', models.CharField(blank=True, max_length=60)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('fallida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_correo', to='financiacion_educativa.decisionrevisioneducativa')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_correo_estado', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Entrega de correo de estado',
                'verbose_name_plural': 'Entregas de correo de estado',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoSeguridadFinanciacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('UNAUTHORIZED_APPLICATION_ACCESS', 'Acceso no autorizado a solicitud'), ('INVITATION_ACCOUNT_MISMATCH', 'Cuenta no coincide con invitacion'), ('REASSOCIATION_ATTEMPT', 'Intento de reasociacion'), ('MOBILE_CAPTURE_CONTEXT_MISMATCH', 'Contexto movil no autorizado')], max_length=50)),
                ('endpoint', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad_financiacion', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_seguridad', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Evento de seguridad de financiacion',
                'verbose_name_plural': 'Eventos de seguridad de financiacion',
                'ordering': ['-creado_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='decisionrevisioneducativa',
            index=models.Index(fields=['solicitud', 'creada_en'], name='dec_rev_edu_sol_fecha'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevisioneducativa',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ['APPROVED', 'REJECTED'])), fields=('solicitud',), name='uniq_dec_fin_edu_final'),
        ),
        migrations.AddIndex(
            model_name='eventoseguridadfinanciacion',
            index=models.Index(fields=['solicitud', 'creado_en'], name='evt_seg_edu_sol_fecha'),
        ),
        migrations.AddIndex(
            model_name='eventoseguridadfinanciacion',
            index=models.Index(fields=['tipo', 'creado_en'], name='evt_seg_edu_tipo_fecha'),
        ),
    ]
