# Generated by Django 5.2 on 2026-08-02 01:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def impedir_reversion_soportes_nulos(apps, schema_editor):
    EvidenciaMatricula = apps.get_model(
        'financiacion_educativa',
        'EvidenciaMatricula',
    )
    if EvidenciaMatricula.objects.filter(documento_soporte__isnull=True).exists():
        raise RuntimeError(
            'No puede revertirse 0011 mientras existan evidencias de matricula '
            'sin documento de soporte. No se modificaron datos.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0010_revision_seguridad_estado_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofinanciacion',
            options={'ordering': ['-cargado_en'], 'permissions': [('escanear_documento_financiacion', 'Puede solicitar escaneos de documentos educativos'), ('revisar_documento_financiacion', 'Puede revisar documentos educativos')], 'verbose_name': 'Documento de financiacion', 'verbose_name_plural': 'Documentos de financiacion'},
        ),
        migrations.AlterField(
            model_name='evidenciamatricula',
            name='documento_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_matricula', to='financiacion_educativa.documentofinanciacion'),
        ),
        migrations.CreateModel(
            name='IntentoEscaneoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('STARTED', 'Iniciado'), ('CLEAN', 'Limpio'), ('INFECTED', 'Amenaza detectada'), ('ERROR', 'Error operativo')], default='STARTED', max_length=20)),
                ('origen', models.CharField(choices=[('ADMIN', 'Administrador'), ('COMMAND', 'Comando de recuperacion')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=60)),
                ('veredicto', models.CharField(blank=True, max_length=30)),
                ('firma_amenaza', models.CharField(blank=True, max_length=120)),
                ('codigo_error', models.CharField(blank=True, max_length=60)),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finalizado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_escaneo', to='financiacion_educativa.documentofinanciacion')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos_documentales_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de escaneo documental',
                'verbose_name_plural': 'Intentos de escaneo documental',
                'ordering': ['documento', 'numero'],
                'indexes': [models.Index(fields=['estado', 'iniciado_en'], name='scan_doc_estado_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero'), name='uniq_intento_scan_doc_num'), models.UniqueConstraint(condition=models.Q(('estado', 'STARTED')), fields=('documento',), name='uniq_intento_scan_doc_activo')],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=impedir_reversion_soportes_nulos,
        ),
    ]
