# Generated by Django 5.2 on 2026-08-03 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0011_alter_documentofinanciacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofinanciacion',
            name='escaneo_requerido_desde',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='documentofinanciacion',
            name='ultimo_intento_limpio',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_autorizados_safe', to='financiacion_educativa.intentoescaneodocumento'),
        ),
        migrations.CreateModel(
            name='ReaperturaEscaneoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=500)),
                ('intentos_adicionales', models.PositiveSmallIntegerField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaperturas_escaneo_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaperturas_escaneo', to='financiacion_educativa.documentofinanciacion')),
            ],
            options={
                'verbose_name': 'Reapertura de escaneo documental',
                'verbose_name_plural': 'Reaperturas de escaneo documental',
                'ordering': ['documento', 'creado_en'],
                'indexes': [models.Index(fields=['documento', 'creado_en'], name='scan_reopen_doc_fecha_idx')],
            },
        ),
    ]
