# Generated by Django 5.2 on 2026-08-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0012_reapertura_escaneo_documental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofinanciacion',
            options={'base_manager_name': 'objects', 'ordering': ['-cargado_en'], 'permissions': [('escanear_documento_financiacion', 'Puede solicitar escaneos de documentos educativos'), ('revisar_documento_financiacion', 'Puede revisar documentos educativos')], 'verbose_name': 'Documento de financiacion', 'verbose_name_plural': 'Documentos de financiacion'},
        ),
    ]
