# Generated by Django 5.2 on 2026-08-04 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0013_alter_documentofinanciacion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionIADocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('STARTED', 'Iniciada'), ('AUTO_APPROVED', 'Aceptacion automatica concluyente'), ('MANUAL_REVIEW', 'Requiere revision manual'), ('ERROR', 'Fallo tecnico')], default='STARTED', max_length=30)),
                ('origen', models.CharField(choices=[('ADMIN', 'Administrador'), ('COMMAND', 'Comando operativo'), ('AUTOMATIC', 'Orquestacion automatica')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=60)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('version_esquema', models.CharField(default='1', max_length=30)),
                ('calidad', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('legibilidad', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('corresponde_tipo', models.BooleanField(blank=True, null=True)),
                ('indicios_imagen_real', models.BooleanField(blank=True, null=True)),
                ('datos_consistentes', models.BooleanField(blank=True, null=True)),
                ('hallazgos', models.JSONField(blank=True, default=list)),
                ('codigo_error', models.CharField(blank=True, max_length=60)),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finalizado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_ia', to='financiacion_educativa.documentofinanciacion')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_ia_documentales_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validacion IA documental',
                'verbose_name_plural': 'Validaciones IA documentales',
                'ordering': ['documento', 'numero'],
                'permissions': [('procesar_validacion_ia_documento', 'Puede procesar validaciones IA de documentos educativos')],
                'indexes': [models.Index(fields=['estado', 'iniciado_en'], name='val_ia_doc_estado_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero'), name='uniq_validacion_ia_doc_num'), models.UniqueConstraint(condition=models.Q(('estado', 'STARTED')), fields=('documento',), name='uniq_validacion_ia_doc_activa')],
            },
        ),
    ]
