# Generated by Django 5.2 on 2026-08-04 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import financiacion_educativa.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0014_validacioniadocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtefactoContractualEducativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PROMISSORY_NOTE', 'Pagare educativo'), ('ENROLLMENT_FORM', 'Ficha de matricula')], max_length=30)),
                ('numero_version', models.PositiveIntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('GENERATED', 'Generado'), ('SENT_FOR_SIGNATURE', 'Enviado a firma'), ('SIGNED', 'Firmado'), ('CANCELLED', 'Cancelado')], default='GENERATED', max_length=30)),
                ('numero_documento', models.CharField(max_length=80)),
                ('version_plantilla', models.CharField(max_length=40)),
                ('archivo', models.FileField(max_length=500, storage=financiacion_educativa.storage.private_document_storage, upload_to=financiacion_educativa.models.ruta_artefacto_contractual_privado)),
                ('hash_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fotografia_financiera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefactos_contractuales', to='financiacion_educativa.condicionesfinancieras')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefactos_contractuales_educativos_generados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefactos_contractuales', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Artefacto contractual educativo',
                'verbose_name_plural': 'Artefactos contractuales educativos',
                'ordering': ['solicitud', 'tipo', '-numero_version'],
                'indexes': [models.Index(fields=['solicitud', 'tipo', 'estado'], name='art_edu_sol_tipo_estado')],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'tipo', 'numero_version'), name='uniq_art_edu_sol_tipo_ver'), models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('solicitud', 'tipo'), name='uniq_art_edu_vigente_tipo'), models.CheckConstraint(condition=models.Q(('tamano_bytes__gt', 0)), name='art_edu_tamano_positivo')],
            },
        ),
    ]
