# Generated by Django 5.2 on 2026-08-04 21:44

import django.core.validators
import django.db.models.deletion
import financiacion_educativa.models
import financiacion_educativa.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0015_artefactocontractualeducativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefactocontractualeducativo',
            name='archivo_firmado',
            field=models.FileField(blank=True, max_length=500, null=True, storage=financiacion_educativa.storage.private_document_storage, upload_to=financiacion_educativa.models.ruta_artefacto_contractual_privado),
        ),
        migrations.AddField(
            model_name='artefactocontractualeducativo',
            name='firmado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artefactocontractualeducativo',
            name='hash_firmado_sha256',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')]),
        ),
        migrations.AddField(
            model_name='artefactocontractualeducativo',
            name='tamano_firmado_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisionrevisioneducativa',
            name='tipo',
            field=models.CharField(choices=[('APPROVED', 'Aprobar expediente y continuar a pagare'), ('REJECTED', 'Rechazar'), ('CORRECTION_REQUESTED', 'Solicitar correcciones')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProcesoFirmaEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(default='ZAPSIGN', max_length=30)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente de envio'), ('SENDING', 'Enviando'), ('SENT', 'Pendiente de firma'), ('SIGNED', 'Firmado'), ('REFUSED', 'Firma rechazada'), ('FAILED', 'Envio fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=30)),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('token_documento_externo', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('destinatario_hmac', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('intentos_envio', models.PositiveSmallIntegerField(default=0)),
                ('codigo_ultimo_error', models.CharField(blank=True, max_length=60)),
                ('envio_iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('rechazado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('artefacto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proceso_firma', to='financiacion_educativa.artefactocontractualeducativo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_firma', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Proceso de firma educativa',
                'verbose_name_plural': 'Procesos de firma educativa',
                'ordering': ['-creado_en'],
                'permissions': [('gestionar_firma_educativa', 'Puede enviar y recuperar firmas educativas')],
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookFirmaEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('tipo_evento', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('IGNORED', 'Ignorado'), ('RETRYABLE_ERROR', 'Fallo recuperable')], default='RECEIVED', max_length=30)),
                ('codigo_resultado', models.CharField(blank=True, max_length=60)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_webhook', to='financiacion_educativa.procesofirmaeducativa')),
            ],
            options={
                'verbose_name': 'Evento de webhook de firma educativa',
                'verbose_name_plural': 'Eventos de webhook de firma educativa',
                'ordering': ['-recibido_en'],
            },
        ),
        migrations.AddIndex(
            model_name='procesofirmaeducativa',
            index=models.Index(fields=['solicitud', 'estado'], name='firma_edu_sol_estado'),
        ),
        migrations.AddIndex(
            model_name='eventowebhookfirmaeducativa',
            index=models.Index(fields=['tipo_evento', 'estado'], name='evt_firma_edu_tipo_estado'),
        ),
    ]
