# Generated by Django 5.2 on 2026-08-13 17:44

import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0017_validacion_ia_estructurada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacioniadocumento',
            name='indicios_imagen_real',
            field=models.BooleanField(blank=True, help_text='Campo compatible con esquema v2; no certifica autenticidad ni liveness.', null=True, verbose_name='captura aparente de documento fisico'),
        ),
        migrations.AlterField(
            model_name='validacioniadocumento',
            name='version_esquema',
            field=models.CharField(default='3', max_length=30),
        ),
        migrations.CreateModel(
            name='ProcesoAutomatizacionEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_expediente', models.PositiveIntegerField()),
                ('version_politica', models.CharField(default='EDU_AUTOMATION_V1', editable=False, max_length=40)),
                ('version_esquema_ia', models.CharField(default='3', editable=False, max_length=30)),
                ('estado', models.CharField(choices=[('QUEUED', 'En cola'), ('RUNNING', 'En ejecucion'), ('RETRYING', 'Pendiente de reintento'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('MANUAL_EXCEPTION', 'Excepcion manual'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='QUEUED', max_length=30)),
                ('etapa_actual', models.CharField(choices=[('SECURITY_SCAN', 'Escaneo de seguridad'), ('DOCUMENT_VALIDATION', 'Validacion documental'), ('DECISION', 'Decision automatica'), ('FINANCIAL_SNAPSHOT', 'Fotografia financiera'), ('CONTRACT_GENERATION', 'Generacion contractual'), ('SIGNATURE_SEND', 'Envio a firma'), ('WAITING_SIGNATURE', 'Espera de firma'), ('COMPLETED', 'Proceso completado')], default='SECURITY_SCAN', max_length=40)),
                ('intento_actual', models.PositiveSmallIntegerField(default=0)),
                ('maximo_intentos', models.PositiveSmallIntegerField(default=3)),
                ('proxima_ejecucion_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_razon', models.CharField(blank=True, choices=[('SECURITY_SCAN_COMPLETED', 'Escaneo completado'), ('MALWARE_DETECTED', 'Amenaza detectada'), ('SECURITY_SCAN_TEMPORARY_ERROR', 'Fallo temporal de escaneo'), ('DOCUMENT_VALIDATION_COMPLETED', 'Validacion documental completada'), ('DOCUMENT_AI_TEMPORARY_ERROR', 'Fallo temporal de IA'), ('DOCUMENT_CORRECTION_REQUIRED', 'Correccion documental requerida'), ('PDF_CONTENT_PROCESSING_REQUIRED', 'Procesamiento de contenido PDF requerido'), ('DOCUMENT_VALIDATION_INCONCLUSIVE', 'Validacion documental inconclusa'), ('DOCUMENT_RESULT_NOT_CONCLUSIVE', 'Resultado documental no concluyente'), ('AUTOMATIC_DECISION_CONTINUE', 'Decision automatica permite continuar'), ('FINANCIAL_SNAPSHOT_LOCKED', 'Fotografia financiera bloqueada'), ('CONTRACTS_GENERATED', 'Contratos generados'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('SIGNATURE_SEND_AMBIGUOUS', 'Envio a firma ambiguo'), ('SIGNATURE_SEND_RETRY_REQUIRED', 'Reintento de firma requerido'), ('SIGNED_WEBHOOK_CONFIRMED', 'Webhook firmado confirmado'), ('SIGNATURE_REFUSED', 'Firma rechazada'), ('SIGNATURE_CANCELLED', 'Firma cancelada'), ('SIGNATURE_EXPIRED', 'Firma vencida'), ('LEASE_EXPIRED', 'Lease vencido'), ('MAX_ATTEMPTS_EXCEEDED', 'Intentos agotados'), ('SCANNER_TIMEOUT', 'Timeout del escaner'), ('SCANNER_UNAVAILABLE', 'Escaner no disponible'), ('PROVIDER_TIMEOUT', 'Timeout del proveedor'), ('PROVIDER_ERROR', 'Error temporal del proveedor'), ('SIGNED_FILE_RECOVERY_FAILED', 'Fallo recuperando archivo firmado'), ('SIGNATURE_SEND_NOT_CONFIRMED', 'Envio de firma no confirmado'), ('INTERNAL_ERROR', 'Error interno controlado')], max_length=60)),
                ('requisitos_correccion', models.JSONField(blank=True, default=list)),
                ('lease_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_vence_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('iniciada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_automatizacion', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Proceso de automatizacion educativa',
                'verbose_name_plural': 'Procesos de automatizacion educativa',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesoAutomatizacionEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapa', models.CharField(choices=[('SECURITY_SCAN', 'Escaneo de seguridad'), ('DOCUMENT_VALIDATION', 'Validacion documental'), ('DECISION', 'Decision automatica'), ('FINANCIAL_SNAPSHOT', 'Fotografia financiera'), ('CONTRACT_GENERATION', 'Generacion contractual'), ('SIGNATURE_SEND', 'Envio a firma'), ('WAITING_SIGNATURE', 'Espera de firma'), ('COMPLETED', 'Proceso completado')], max_length=40)),
                ('estado', models.CharField(choices=[('QUEUED', 'En cola'), ('RUNNING', 'En ejecucion'), ('RETRYING', 'Pendiente de reintento'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('MANUAL_EXCEPTION', 'Excepcion manual'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], max_length=30)),
                ('intento', models.PositiveSmallIntegerField()),
                ('codigo_razon', models.CharField(blank=True, choices=[('SECURITY_SCAN_COMPLETED', 'Escaneo completado'), ('MALWARE_DETECTED', 'Amenaza detectada'), ('SECURITY_SCAN_TEMPORARY_ERROR', 'Fallo temporal de escaneo'), ('DOCUMENT_VALIDATION_COMPLETED', 'Validacion documental completada'), ('DOCUMENT_AI_TEMPORARY_ERROR', 'Fallo temporal de IA'), ('DOCUMENT_CORRECTION_REQUIRED', 'Correccion documental requerida'), ('PDF_CONTENT_PROCESSING_REQUIRED', 'Procesamiento de contenido PDF requerido'), ('DOCUMENT_VALIDATION_INCONCLUSIVE', 'Validacion documental inconclusa'), ('DOCUMENT_RESULT_NOT_CONCLUSIVE', 'Resultado documental no concluyente'), ('AUTOMATIC_DECISION_CONTINUE', 'Decision automatica permite continuar'), ('FINANCIAL_SNAPSHOT_LOCKED', 'Fotografia financiera bloqueada'), ('CONTRACTS_GENERATED', 'Contratos generados'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('SIGNATURE_SEND_AMBIGUOUS', 'Envio a firma ambiguo'), ('SIGNATURE_SEND_RETRY_REQUIRED', 'Reintento de firma requerido'), ('SIGNED_WEBHOOK_CONFIRMED', 'Webhook firmado confirmado'), ('SIGNATURE_REFUSED', 'Firma rechazada'), ('SIGNATURE_CANCELLED', 'Firma cancelada'), ('SIGNATURE_EXPIRED', 'Firma vencida'), ('LEASE_EXPIRED', 'Lease vencido'), ('MAX_ATTEMPTS_EXCEEDED', 'Intentos agotados'), ('SCANNER_TIMEOUT', 'Timeout del escaner'), ('SCANNER_UNAVAILABLE', 'Escaner no disponible'), ('PROVIDER_TIMEOUT', 'Timeout del proveedor'), ('PROVIDER_ERROR', 'Error temporal del proveedor'), ('SIGNED_FILE_RECOVERY_FAILED', 'Fallo recuperando archivo firmado'), ('SIGNATURE_SEND_NOT_CONFIRMED', 'Envio de firma no confirmado'), ('INTERNAL_ERROR', 'Error interno controlado')], max_length=60)),
                ('metadata_publica', models.JSONField(blank=True, default=dict)),
                ('iniciada_en', models.DateTimeField()),
                ('finalizada_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='financiacion_educativa.procesoautomatizacioneducativa')),
            ],
            options={
                'verbose_name': 'Etapa de automatizacion educativa',
                'verbose_name_plural': 'Etapas de automatizacion educativa',
                'ordering': ['proceso', 'iniciada_en', 'id'],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='procesoautomatizacioneducativa',
            index=models.Index(fields=['estado', 'proxima_ejecucion_en'], name='auto_edu_estado_proxima'),
        ),
        migrations.AddIndex(
            model_name='procesoautomatizacioneducativa',
            index=models.Index(fields=['estado', 'lease_vence_en'], name='auto_edu_estado_lease'),
        ),
        migrations.AddConstraint(
            model_name='procesoautomatizacioneducativa',
            constraint=models.UniqueConstraint(fields=('solicitud', 'version_expediente'), name='uniq_auto_edu_sol_version'),
        ),
        migrations.AddConstraint(
            model_name='procesoautomatizacioneducativa',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['QUEUED', 'RUNNING', 'RETRYING', 'PENDING_SIGNATURE'])), fields=('solicitud',), name='uniq_auto_edu_sol_activo'),
        ),
        migrations.AddConstraint(
            model_name='procesoautomatizacioneducativa',
            constraint=models.CheckConstraint(condition=models.Q(('maximo_intentos__gt', 0)), name='auto_edu_max_intentos_pos'),
        ),
        migrations.AddConstraint(
            model_name='procesoautomatizacioneducativa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'RUNNING'), ('lease_id__isnull', False), ('lease_vence_en__isnull', False)), models.Q(models.Q(('estado', 'RUNNING'), _negated=True), ('lease_id__isnull', True), ('lease_vence_en__isnull', True)), _connector='OR'), name='auto_edu_lease_consistente'),
        ),
        migrations.AddIndex(
            model_name='etapaprocesoautomatizacioneducativa',
            index=models.Index(fields=['proceso', 'etapa'], name='auto_edu_proc_etapa'),
        ),
        migrations.AddConstraint(
            model_name='etapaprocesoautomatizacioneducativa',
            constraint=models.UniqueConstraint(fields=('proceso', 'etapa', 'intento'), name='uniq_auto_edu_etapa_intento'),
        ),
    ]
