# Generated by Django 5.2 on 2026-08-13 20:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0018_alter_validacioniadocumento_indicios_imagen_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxCorreoEducativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('INITIAL_INVITATION', 'Invitacion inicial'), ('INVITATION_REISSUE', 'Reemision de invitacion'), ('MOBILE_CAPTURE_LINK', 'Enlace de captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica')], max_length=40)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('evento_logico', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('destinatarios', models.JSONField(default=list)),
                ('destinatarios_copia', models.JSONField(blank=True, default=list)),
                ('codigo_mensaje', models.CharField(choices=[('INVITATION', 'Invitacion de continuacion'), ('MOBILE_CAPTURE', 'Captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica')], max_length=40)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'En envio'), ('RETRYING', 'Pendiente de reintento'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('AMBIGUOUS', 'Entrega ambigua')], default='PENDING', max_length=20)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('maximo_intentos', models.PositiveSmallIntegerField(default=3)),
                ('proxima_ejecucion_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_vence_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('message_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('codigo_ultimo_error', models.CharField(blank=True, max_length=60)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('decision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correo_outbox', to='financiacion_educativa.decisionrevisioneducativa')),
                ('enlace_captura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correo_outbox', to='financiacion_educativa.enlacecapturamovil')),
                ('entrega_invitacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correo_outbox', to='financiacion_educativa.entregainvitacioncontinuacion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correos_outbox', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Correo educativo en outbox',
                'verbose_name_plural': 'Correos educativos en outbox',
                'ordering': ['proxima_ejecucion_en', 'creada_en'],
                'indexes': [models.Index(fields=['estado', 'proxima_ejecucion_en'], name='out_email_estado_prox'), models.Index(fields=['estado', 'lease_vence_en'], name='out_email_estado_lease'), models.Index(fields=['solicitud', 'tipo_evento'], name='out_email_sol_evento')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'SENT')), fields=('evento_logico',), name='uniq_out_email_evento_sent'), models.CheckConstraint(condition=models.Q(('intentos__gte', 0)), name='out_email_intentos_nn'), models.CheckConstraint(condition=models.Q(('maximo_intentos__gt', 0)), name='out_email_max_int_pos'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'SENDING'), ('lease_id__isnull', False), ('lease_vence_en__isnull', False)), models.Q(models.Q(('estado', 'SENDING'), _negated=True), ('lease_id__isnull', True), ('lease_vence_en__isnull', True)), _connector='OR'), name='out_email_lease_consist')],
            },
        ),
    ]
