# Generated by Django 5.2 on 2026-08-13 22:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0019_outboxcorreoeducativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaprocesoautomatizacioneducativa',
            name='codigo_razon',
            field=models.CharField(blank=True, choices=[('SECURITY_SCAN_COMPLETED', 'Escaneo completado'), ('MALWARE_DETECTED', 'Amenaza detectada'), ('SECURITY_SCAN_TEMPORARY_ERROR', 'Fallo temporal de escaneo'), ('DOCUMENT_VALIDATION_COMPLETED', 'Validacion documental completada'), ('DOCUMENT_AI_TEMPORARY_ERROR', 'Fallo temporal de IA'), ('DOCUMENT_CONTENT_TEMPORARY_ERROR', 'Fallo temporal procesando contenido'), ('DOCUMENT_CONTENT_PERMANENT_ERROR', 'Fallo permanente procesando contenido'), ('DOCUMENT_CORRECTION_REQUIRED', 'Correccion documental requerida'), ('PDF_CONTENT_PROCESSING_REQUIRED', 'Procesamiento de contenido PDF requerido'), ('DOCUMENT_VALIDATION_INCONCLUSIVE', 'Validacion documental inconclusa'), ('DOCUMENT_RESULT_NOT_CONCLUSIVE', 'Resultado documental no concluyente'), ('AUTOMATIC_DECISION_CONTINUE', 'Decision automatica permite continuar'), ('FINANCIAL_SNAPSHOT_LOCKED', 'Fotografia financiera bloqueada'), ('CONTRACTS_GENERATED', 'Contratos generados'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('SIGNATURE_SEND_AMBIGUOUS', 'Envio a firma ambiguo'), ('SIGNATURE_SEND_RETRY_REQUIRED', 'Reintento de firma requerido'), ('SIGNED_WEBHOOK_CONFIRMED', 'Webhook firmado confirmado'), ('SIGNATURE_REFUSED', 'Firma rechazada'), ('SIGNATURE_CANCELLED', 'Firma cancelada'), ('SIGNATURE_EXPIRED', 'Firma vencida'), ('LEASE_EXPIRED', 'Lease vencido'), ('MAX_ATTEMPTS_EXCEEDED', 'Intentos agotados'), ('SCANNER_TIMEOUT', 'Timeout del escaner'), ('SCANNER_UNAVAILABLE', 'Escaner no disponible'), ('PROVIDER_TIMEOUT', 'Timeout del proveedor'), ('PROVIDER_ERROR', 'Error temporal del proveedor'), ('SIGNED_FILE_RECOVERY_FAILED', 'Fallo recuperando archivo firmado'), ('SIGNATURE_SEND_NOT_CONFIRMED', 'Envio de firma no confirmado'), ('INTERNAL_ERROR', 'Error interno controlado')], max_length=60),
        ),
        migrations.AlterField(
            model_name='procesoautomatizacioneducativa',
            name='codigo_razon',
            field=models.CharField(blank=True, choices=[('SECURITY_SCAN_COMPLETED', 'Escaneo completado'), ('MALWARE_DETECTED', 'Amenaza detectada'), ('SECURITY_SCAN_TEMPORARY_ERROR', 'Fallo temporal de escaneo'), ('DOCUMENT_VALIDATION_COMPLETED', 'Validacion documental completada'), ('DOCUMENT_AI_TEMPORARY_ERROR', 'Fallo temporal de IA'), ('DOCUMENT_CONTENT_TEMPORARY_ERROR', 'Fallo temporal procesando contenido'), ('DOCUMENT_CONTENT_PERMANENT_ERROR', 'Fallo permanente procesando contenido'), ('DOCUMENT_CORRECTION_REQUIRED', 'Correccion documental requerida'), ('PDF_CONTENT_PROCESSING_REQUIRED', 'Procesamiento de contenido PDF requerido'), ('DOCUMENT_VALIDATION_INCONCLUSIVE', 'Validacion documental inconclusa'), ('DOCUMENT_RESULT_NOT_CONCLUSIVE', 'Resultado documental no concluyente'), ('AUTOMATIC_DECISION_CONTINUE', 'Decision automatica permite continuar'), ('FINANCIAL_SNAPSHOT_LOCKED', 'Fotografia financiera bloqueada'), ('CONTRACTS_GENERATED', 'Contratos generados'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('SIGNATURE_SEND_AMBIGUOUS', 'Envio a firma ambiguo'), ('SIGNATURE_SEND_RETRY_REQUIRED', 'Reintento de firma requerido'), ('SIGNED_WEBHOOK_CONFIRMED', 'Webhook firmado confirmado'), ('SIGNATURE_REFUSED', 'Firma rechazada'), ('SIGNATURE_CANCELLED', 'Firma cancelada'), ('SIGNATURE_EXPIRED', 'Firma vencida'), ('LEASE_EXPIRED', 'Lease vencido'), ('MAX_ATTEMPTS_EXCEEDED', 'Intentos agotados'), ('SCANNER_TIMEOUT', 'Timeout del escaner'), ('SCANNER_UNAVAILABLE', 'Escaner no disponible'), ('PROVIDER_TIMEOUT', 'Timeout del proveedor'), ('PROVIDER_ERROR', 'Error temporal del proveedor'), ('SIGNED_FILE_RECOVERY_FAILED', 'Fallo recuperando archivo firmado'), ('SIGNATURE_SEND_NOT_CONFIRMED', 'Envio de firma no confirmado'), ('INTERNAL_ERROR', 'Error interno controlado')], max_length=60),
        ),
        migrations.CreateModel(
            name='ProcesamientoContenidoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('hash_original', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='La evidencia debe ser un hash SHA-256 hexadecimal.', regex='^[0-9a-f]{64}$')])),
                ('content_type', models.CharField(max_length=120)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('numero_paginas', models.PositiveSmallIntegerField(default=1)),
                ('pdf_cifrado', models.BooleanField(default=False)),
                ('contenido_activo_detectado', models.BooleanField(default=False)),
                ('metodo_extraccion', models.CharField(blank=True, choices=[('IMAGE', 'Imagen original'), ('PDF_TEXT', 'Texto PDF'), ('PDF_RENDER', 'Paginas PDF renderizadas'), ('PDF_HYBRID', 'Texto y paginas renderizadas')], max_length=30)),
                ('paginas_analizadas', models.JSONField(blank=True, default=list)),
                ('version_procesador', models.CharField(default='PDF_CONTENT_V1', max_length=30)),
                ('version_esquema', models.CharField(default='CONTENT_V1', max_length=30)),
                ('version_politica', models.CharField(default='EDU_CONTENT_V1', max_length=40)),
                ('estado', models.CharField(choices=[('STARTED', 'Iniciado'), ('ACCEPTED', 'Aceptado'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('RETRYING', 'Pendiente de reintento'), ('MANUAL_EXCEPTION', 'Excepcion manual'), ('FAILED', 'Fallido'), ('OBSOLETE', 'Version obsoleta')], default='STARTED', max_length=30)),
                ('clasificacion', models.CharField(blank=True, choices=[('EMPLOYMENT_CERTIFICATE', 'Certificado laboral'), ('INCOME_CERTIFICATE', 'Certificado de ingresos'), ('INCOME_AND_WITHHOLDING_CERTIFICATE', 'Certificado de ingresos y retenciones'), ('BANK_STATEMENT', 'Extracto bancario'), ('PAYSLIP', 'Desprendible de nomina'), ('ENROLLMENT_EVIDENCE', 'Soporte de matricula'), ('UNRELATED', 'Documento ajeno'), ('INCONCLUSIVE', 'No concluyente')], max_length=50)),
                ('campos_estructurados', models.JSONField(blank=True, default=dict)),
                ('codigos_razon', models.JSONField(blank=True, default=list)),
                ('confianzas', models.JSONField(blank=True, default=dict)),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finalizado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesamientos_contenido', to='financiacion_educativa.documentofinanciacion')),
            ],
            options={
                'verbose_name': 'Procesamiento de contenido documental',
                'verbose_name_plural': 'Procesamientos de contenido documental',
                'ordering': ['documento', 'numero'],
                'base_manager_name': 'objects',
                'permissions': [('procesar_contenido_documento', 'Puede procesar contenido de documentos educativos')],
                'indexes': [models.Index(fields=['estado', 'iniciado_en'], name='proc_cont_estado_fecha'), models.Index(fields=['documento', 'hash_original'], name='proc_cont_doc_hash')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero'), name='uniq_proc_cont_doc_num'), models.UniqueConstraint(condition=models.Q(('estado', 'STARTED')), fields=('documento',), name='uniq_proc_cont_doc_activo')],
            },
        ),
    ]
