# Generated by Django 5.2 on 2026-08-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0020_procesamiento_contenido_documental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudfinanciacioneducativa',
            options={'ordering': ['-creada_en'], 'permissions': [('revisar_solicitud_financiacion', 'Puede revisar y decidir solicitudes educativas'), ('acceder_dashboard_operativo', 'Puede acceder al dashboard operativo educativo'), ('consultar_solicitudes_operativas', 'Puede consultar solicitudes educativas globales'), ('consultar_documentos_validaciones_operativas', 'Puede consultar documentos y validaciones educativas'), ('consultar_procesos_excepciones_operativas', 'Puede consultar procesos y excepciones educativas'), ('consultar_datos_integrales_operativos', 'Puede consultar datos personales integrales educativos')], 'verbose_name': 'Solicitud de financiacion educativa', 'verbose_name_plural': 'Solicitudes de financiacion educativa'},
        ),
    ]
