# Generated by Django 5.2 on 2026-08-19 01:10

import django.db.models.deletion
import django.utils.timezone
import financiacion_educativa.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0021_permisos_dashboard_operativo'),
        ('instituciones', '0002_membresiainstitucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofinanciacion',
            options={'base_manager_name': 'objects', 'ordering': ['-cargado_en'], 'permissions': [('escanear_documento_financiacion', 'Puede solicitar escaneos de documentos educativos'), ('revisar_documento_financiacion', 'Puede revisar documentos educativos'), ('acceder_revision_documental_operativa', 'Puede acceder a la revision documental operativa'), ('decidir_revision_documental_operativa', 'Puede decidir revisiones documentales operativas')], 'verbose_name': 'Documento de financiacion', 'verbose_name_plural': 'Documentos de financiacion'},
        ),
        migrations.CreateModel(
            name='DecisionRevisionDocumentoOperativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('ACCEPTED', 'Documento aceptado'), ('CORRECTION_REQUESTED', 'Correccion solicitada')], max_length=30)),
                ('motivo', models.CharField(blank=True, choices=[('UNREADABLE', 'Documento ilegible'), ('INCOMPLETE', 'Documento incompleto'), ('WRONG_DOCUMENT', 'Tipo documental incorrecto'), ('EXPIRED', 'Documento vencido'), ('DATA_MISMATCH', 'Datos no coinciden'), ('OTHER', 'Otro motivo controlado')], max_length=30)),
                ('observacion_publica', models.CharField(blank=True, max_length=500)),
                ('nota_interna', models.CharField(blank=True, max_length=1000)),
                ('estado_documento_anterior', models.CharField(choices=[('PENDING', 'Pendiente de revision'), ('APPROVED', 'Aceptado'), ('REJECTED', 'Rechazado')], max_length=20)),
                ('estado_documento_posterior', models.CharField(choices=[('PENDING', 'Pendiente de revision'), ('APPROVED', 'Aceptado'), ('REJECTED', 'Rechazado')], max_length=20)),
                ('estado_solicitud_anterior', models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('APPROVED', 'Aprobada; curso autorizado'), ('REJECTED', 'Rechazada'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40)),
                ('estado_solicitud_posterior', models.CharField(choices=[('PENDING_USER_REGISTRATION', 'Pendiente de registro del usuario'), ('PENDING_TERMS', 'Pendiente de terminos'), ('PENDING_DOCUMENT', 'Pendiente de documento'), ('PENDING_GUARDIAN', 'Pendiente de tutor'), ('PENDING_MANUAL_REVIEW', 'Pendiente de revision manual'), ('CORRECTION_REQUIRED', 'Correccion requerida'), ('APPROVED', 'Aprobada; curso autorizado'), ('REJECTED', 'Rechazada'), ('PENDING_PROMISSORY_NOTE', 'Pendiente de pagare'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('ACTIVE', 'Activa'), ('PAYMENT_REPORTED', 'Pago reportado'), ('PAYMENT_UNDER_REVIEW', 'Pago en revision'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], max_length=40)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_documentales_operativas', to=settings.AUTH_USER_MODEL)),
                ('decision_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_documentales', to='financiacion_educativa.decisionrevisioneducativa')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_operativas', to='financiacion_educativa.documentofinanciacion')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_documentales_operativas', to='instituciones.institucion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_documentales_operativas', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'verbose_name': 'Decision operativa de documento',
                'verbose_name_plural': 'Decisiones operativas de documentos',
                'ordering': ['-creada_en', '-id'],
                'indexes': [models.Index(fields=['documento', 'creada_en'], name='dec_doc_op_doc_fecha')],
            },
            bases=(financiacion_educativa.models.ModeloInmutableMixin, models.Model),
        ),
    ]
