# Generated by Django 5.2 on 2026-09-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0022_revision_documental_operativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregainvitacioncontinuacion',
            name='origen',
            field=models.CharField(choices=[('INITIAL', 'Inicial'), ('AUTOMATIC_RETRY', 'Reintento automatico'), ('MANUAL_REISSUE', 'Reemision manual'), ('SCHEDULED_REMINDER', 'Recordatorio programado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='outboxcorreoeducativo',
            name='codigo_mensaje',
            field=models.CharField(choices=[('INVITATION', 'Invitacion de continuacion'), ('NEW_APPLICATION_INTERNAL', 'Nueva solicitud para operaciones'), ('MOBILE_CAPTURE', 'Captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica')], max_length=40),
        ),
        migrations.AlterField(
            model_name='outboxcorreoeducativo',
            name='tipo_evento',
            field=models.CharField(choices=[('INITIAL_INVITATION', 'Invitacion inicial'), ('INVITATION_REISSUE', 'Reemision de invitacion'), ('CONTINUATION_REMINDER_1H', 'Recordatorio de continuacion 1 hora'), ('CONTINUATION_REMINDER_6H', 'Recordatorio de continuacion 6 horas'), ('CONTINUATION_REMINDER_24H', 'Recordatorio de continuacion 24 horas'), ('CONTINUATION_REMINDER_48H', 'Recordatorio de continuacion 48 horas'), ('NEW_APPLICATION_INTERNAL', 'Nueva solicitud para operaciones'), ('MOBILE_CAPTURE_LINK', 'Enlace de captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica')], max_length=40),
        ),
    ]
