# Generated by Django 5.2 on 2026-09-02 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0023_alter_entregainvitacioncontinuacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentofinanciacion',
            name='doc_identidad_origen_camara',
        ),
        migrations.AlterField(
            model_name='documentofinanciacion',
            name='origen_captura',
            field=models.CharField(choices=[('INSTITUTION_API', 'API institucional'), ('USER_UPLOAD', 'Carga del usuario'), ('CAMERA', 'Camara'), ('WEBRTC_CAMERA', 'Camara WebRTC'), ('NATIVE_CAMERA_FALLBACK', 'Camara nativa del telefono'), ('INTERNAL', 'Generado internamente')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='documentofinanciacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ('STUDENT_ID_FRONT', 'STUDENT_ID_BACK', 'GUARDIAN_ID_FRONT', 'GUARDIAN_ID_BACK')), _negated=True), ('origen_captura__in', ('CAMERA', 'WEBRTC_CAMERA', 'NATIVE_CAMERA_FALLBACK')), _connector='OR'), name='doc_identidad_origen_camara'),
        ),
    ]
