# Generated by Django 5.2 on 2026-09-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0024_remove_documentofinanciacion_doc_identidad_origen_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesamientocontenidodocumento',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('EMPLOYMENT_CERTIFICATE', 'Certificado laboral'), ('INCOME_CERTIFICATE', 'Certificado de ingresos'), ('INCOME_AND_WITHHOLDING_CERTIFICATE', 'Certificado de ingresos y retenciones'), ('BANK_STATEMENT', 'Extracto bancario'), ('BANK_ACCOUNT_CERTIFICATE', 'Certificacion bancaria de titularidad'), ('PAYSLIP', 'Desprendible de nomina'), ('ENROLLMENT_EVIDENCE', 'Soporte de matricula'), ('UNRELATED', 'Documento ajeno'), ('INCONCLUSIVE', 'No concluyente')], max_length=50),
        ),
    ]
