# Generated by Django 5.2 on 2026-09-03 19:48

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0025_alter_procesamientocontenidodocumento_clasificacion'),
        ('instituciones', '0002_membresiainstitucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioNotificacionInstitucionalEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatario institucional educativo',
                'verbose_name_plural': 'Destinatarios institucionales educativos',
                'ordering': ['institucion__nombre_comercial', 'correo'],
            },
        ),
        migrations.AddField(
            model_name='outboxcorreoeducativo',
            name='correo_origen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copias_secundarias', to='financiacion_educativa.outboxcorreoeducativo'),
        ),
        migrations.AlterField(
            model_name='outboxcorreoeducativo',
            name='codigo_mensaje',
            field=models.CharField(choices=[('INVITATION', 'Invitacion de continuacion'), ('NEW_APPLICATION_INTERNAL', 'Nueva solicitud para operaciones'), ('MOBILE_CAPTURE', 'Captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica'), ('AUDIT_COPY', 'Copia de auditoria'), ('INSTITUTIONAL_INITIAL_NOTIFICATION', 'Notificacion institucional de invitacion inicial')], max_length=40),
        ),
        migrations.AlterField(
            model_name='outboxcorreoeducativo',
            name='tipo_evento',
            field=models.CharField(choices=[('INITIAL_INVITATION', 'Invitacion inicial'), ('INVITATION_REISSUE', 'Reemision de invitacion'), ('CONTINUATION_REMINDER_1H', 'Recordatorio de continuacion 1 hora'), ('CONTINUATION_REMINDER_6H', 'Recordatorio de continuacion 6 horas'), ('CONTINUATION_REMINDER_24H', 'Recordatorio de continuacion 24 horas'), ('CONTINUATION_REMINDER_48H', 'Recordatorio de continuacion 48 horas'), ('NEW_APPLICATION_INTERNAL', 'Nueva solicitud para operaciones'), ('MOBILE_CAPTURE_LINK', 'Enlace de captura movil'), ('DOSSIER_RECEIVED', 'Expediente recibido'), ('REVIEW_DECISION', 'Decision de revision'), ('AUTOMATIC_CORRECTION', 'Correccion automatica'), ('AUTOMATIC_CONTINUATION', 'Continuacion automatica'), ('AUDIT_COPY', 'Copia de auditoria'), ('INSTITUTIONAL_INITIAL_NOTIFICATION', 'Notificacion institucional de invitacion inicial')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='outboxcorreoeducativo',
            index=models.Index(fields=['correo_origen', 'codigo_mensaje'], name='out_email_origin_code'),
        ),
        migrations.AddConstraint(
            model_name='outboxcorreoeducativo',
            constraint=models.UniqueConstraint(condition=models.Q(('correo_origen__isnull', False)), fields=('correo_origen', 'codigo_mensaje'), name='uniq_out_email_origin_code'),
        ),
        migrations.AddConstraint(
            model_name='outboxcorreoeducativo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo_mensaje__in', ['AUDIT_COPY', 'INSTITUTIONAL_INITIAL_NOTIFICATION']), ('correo_origen__isnull', False)), models.Q(('correo_origen__isnull', True), models.Q(('codigo_mensaje__in', ['AUDIT_COPY', 'INSTITUTIONAL_INITIAL_NOTIFICATION']), _negated=True)), _connector='OR'), name='out_email_origin_consist'),
        ),
        migrations.AddConstraint(
            model_name='outboxcorreoeducativo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo_mensaje', 'AUDIT_COPY'), ('tipo_evento', 'AUDIT_COPY')), models.Q(('codigo_mensaje', 'INSTITUTIONAL_INITIAL_NOTIFICATION'), ('tipo_evento', 'INSTITUTIONAL_INITIAL_NOTIFICATION')), models.Q(models.Q(('codigo_mensaje__in', ['AUDIT_COPY', 'INSTITUTIONAL_INITIAL_NOTIFICATION']), _negated=True), models.Q(('tipo_evento__in', ['AUDIT_COPY', 'INSTITUTIONAL_INITIAL_NOTIFICATION']), _negated=True)), _connector='OR'), name='out_email_copy_type_match'),
        ),
        migrations.AddConstraint(
            model_name='outboxcorreoeducativo',
            constraint=models.CheckConstraint(condition=models.Q(('correo_origen__isnull', True), models.Q(('contexto', {}), ('destinatarios_copia', [])), _connector='OR'), name='out_email_copy_min_data'),
        ),
        migrations.AddField(
            model_name='destinatarionotificacioninstitucionaleducativa',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatarios_notificacion_educativa', to='instituciones.institucion'),
        ),
        migrations.AddIndex(
            model_name='destinatarionotificacioninstitucionaleducativa',
            index=models.Index(fields=['institucion', 'activo'], name='edu_inst_notice_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='destinatarionotificacioninstitucionaleducativa',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), models.F('institucion'), name='uniq_edu_inst_notice_email'),
        ),
    ]
