# Generated by Django 5.2 on 2026-09-27 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion_educativa', '0026_copias_auditoria_institucionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPublicoSandboxSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_publico', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=8)),
                ('course_authorized', models.BooleanField()),
                ('decision_reason', models.CharField(blank=True, default='', max_length=40)),
                ('condiciones_financieras', models.JSONField(blank=True, default=dict)),
                ('configuracion_financiera', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado_sandbox', to='financiacion_educativa.solicitudfinanciacioneducativa')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course_authorized', True), ('decision_reason', ''), ('estado_publico', 'APPROVED'), models.Q(('condiciones_financieras', {}), _negated=True)), models.Q(('condiciones_financieras', {}), ('course_authorized', False), ('decision_reason__in', ['INCOMPLETE_INFORMATION', 'UNREADABLE_DOCUMENT', 'IDENTITY_MISMATCH', 'GUARDIANSHIP_NOT_VERIFIED', 'ENROLLMENT_NOT_VERIFIED', 'OTHER']), ('estado_publico', 'REJECTED')), _connector='OR'), name='edu_sandbox_result_coherent')],
            },
        ),
    ]
