# Generated by Django 5.2 on 2026-05-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0030_pagocomisionejecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInternalAPIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('product_type', models.CharField(blank=True, max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('document_number_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('document_number_masked', models.CharField(blank=True, max_length=20)),
                ('phone_masked', models.CharField(blank=True, max_length=20)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoria API interna WhatsApp',
                'verbose_name_plural': 'Auditoria API interna WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='wa_audit_action_created_idx'), models.Index(fields=['document_number_hash'], name='wa_audit_doc_hash_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInternalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('payroll_loan', 'Libranza'), ('whatsapp_credit', 'Credito WhatsApp')], max_length=32)),
                ('source', models.CharField(default='whatsapp', max_length=32)),
                ('document_number', models.CharField(db_index=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('consent_type', models.CharField(max_length=80)),
                ('accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consentimiento interno WhatsApp',
                'verbose_name_plural': 'Consentimientos internos WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'document_number', 'consent_type'], name='wa_consent_product_doc_idx'), models.Index(fields=['-created_at'], name='wa_consent_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInternalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('payroll_loan', 'Libranza'), ('whatsapp_credit', 'Credito WhatsApp')], max_length=32)),
                ('source', models.CharField(default='whatsapp', max_length=32)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('pending_payroll_validation', 'Pendiente validacion convenio'), ('pending_form_completion', 'Pendiente completar formulario'), ('rejected', 'Rechazada')], default='received', max_length=40)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(db_index=True, max_length=30)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('ocupacion', models.CharField(blank=True, max_length=120)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.PositiveSmallIntegerField()),
                ('convenio_validado', models.BooleanField(default=False)),
                ('vinculo_laboral_validado', models.BooleanField(default=False)),
                ('autorizacion_tratamiento_datos', models.BooleanField(default=False)),
                ('autorizacion_validacion_informacion', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_creditos.empresa')),
            ],
            options={
                'verbose_name': 'Solicitud interna WhatsApp',
                'verbose_name_plural': 'Solicitudes internas WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'numero_documento', '-created_at'], name='wa_app_product_doc_idx'), models.Index(fields=['status', '-created_at'], name='wa_app_status_created_idx')],
            },
        ),
    ]
