# Generated by Django 5.2 on 2026-07-24 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=160)),
                ('razon_social', models.CharField(max_length=200)),
                ('tipo_identificacion_tributaria', models.CharField(choices=[('NIT', 'NIT'), ('OTRO', 'Otro')], default='NIT', max_length=20)),
                ('numero_identificacion_tributaria', models.CharField(max_length=40)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre_comercial'],
                'indexes': [models.Index(fields=['activa', 'nombre_comercial'], name='inst_activa_nombre_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo_identificacion_tributaria', 'numero_identificacion_tributaria'), name='uniq_institucion_identificacion')],
            },
        ),
        migrations.CreateModel(
            name='CredencialAPIInstitucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo_clave', models.CharField(db_index=True, max_length=16)),
                ('secreto_hash', models.CharField(max_length=128)),
                ('alcances', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_api', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'Credencial API de institucion',
                'verbose_name_plural': 'Credenciales API de instituciones',
                'ordering': ['institucion__nombre_comercial', 'nombre'],
                'indexes': [models.Index(fields=['institucion', 'activa'], name='cred_inst_activa_idx')],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'nombre'), name='uniq_credencial_nombre_institucion'), models.UniqueConstraint(fields=('prefijo_clave',), name='uniq_credencial_prefijo')],
            },
        ),
    ]
