# Generated by Django 5.2 on 2026-08-18 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembresiaInstitucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('INSTITUTION_ADMIN', 'Administrador institucional'), ('INSTITUTION_ANALYST', 'Analista institucional'), ('INSTITUTION_READ_ONLY', 'Solo lectura')], max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('invitado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activado_en', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('desactivado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_institucionales_creadas', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='instituciones.institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias_institucionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresia institucional',
                'verbose_name_plural': 'Membresias institucionales',
                'ordering': ['institucion__nombre_comercial', 'usuario__email'],
                'indexes': [models.Index(fields=['institucion', 'activa', 'rol'], name='memb_inst_activa_rol_idx'), models.Index(fields=['usuario', 'activa'], name='memb_usuario_activa_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'institucion'), name='uniq_membresia_usuario_institucion'), models.CheckConstraint(condition=models.Q(models.Q(('activa', True), ('activado_en__isnull', False), ('desactivado_en__isnull', True)), ('activa', False), _connector='OR'), name='membresia_activa_fechas_consistentes')],
            },
        ),
    ]
