# Generated by Django 5.2 on 2026-05-24 21:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('subdomain', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['subdomain', 'is_active'], name='contractor_subdomain_idx'), models.Index(fields=['slug'], name='contractor_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractorProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('contractor_credit', 'Credito contratista')], default='contractor_credit', max_length=40)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_term_months', models.PositiveSmallIntegerField(default=1)),
                ('max_term_months', models.PositiveSmallIntegerField()),
                ('monthly_rate', models.DecimalField(decimal_places=4, help_text='Tasa mensual porcentual.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Comision porcentual sobre el monto solicitado.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('19.0000'), help_text='IVA porcentual sobre la comision.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('allows_second_credit', models.BooleanField(default=False)),
                ('allows_portfolio_takeover', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='contractors.contractororganization')),
            ],
            options={
                'ordering': ['organization__name', 'product_type'],
                'indexes': [models.Index(fields=['organization', 'product_type', 'is_active'], name='contractor_product_cfg_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'product_type'), name='unique_active_contractor_product_config')],
            },
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='contractors.contractororganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', 'user_id'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='contractor_profile_user_idx'), models.Index(fields=['organization', 'is_active'], name='contractor_profile_org_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_contractor_profile_user_org')],
            },
        ),
    ]
