# Generated by Django 5.2 on 2026-05-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contractors/branding/logos/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('landing_copy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='contractors.contractororganization')),
            ],
            options={
                'ordering': ['organization__name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='contractor_branding_org_idx')],
            },
        ),
    ]
