# Generated by Django 5.2 on 2026-05-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_contractorbranding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorbranding',
            options={'ordering': ['organization__name'], 'verbose_name': 'Marca contratista', 'verbose_name_plural': 'Marcas contratistas'},
        ),
        migrations.AlterModelOptions(
            name='contractororganization',
            options={'ordering': ['name'], 'verbose_name': 'Organizacion contratista', 'verbose_name_plural': 'Organizaciones contratistas'},
        ),
        migrations.AlterModelOptions(
            name='contractorproductconfig',
            options={'ordering': ['organization__name', 'product_type'], 'verbose_name': 'Configuracion de producto contratista', 'verbose_name_plural': 'Configuraciones de producto contratista'},
        ),
        migrations.AlterModelOptions(
            name='contractorprofile',
            options={'ordering': ['organization__name', 'user_id'], 'verbose_name': 'Perfil contratista', 'verbose_name_plural': 'Perfiles contratistas'},
        ),
    ]
