# Generated by Django 5.2 on 2026-05-25 01:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_alter_contractorbranding_options_and_more'),
        ('gestion_creditos', '0034_add_risk_diagnostic_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revision'), ('RECHAZADA', 'Rechazada'), ('CONVERTIDA', 'Convertida')], default='RECIBIDA', max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('term_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('simulation_payload', models.JSONField(blank=True, default=dict)),
                ('document_type', models.CharField(max_length=30)),
                ('document_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('source_subdomain', models.SlugField(max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_applications', to='gestion_creditos.credito')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='contractors.contractororganization')),
                ('product_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='contractors.contractorproductconfig')),
            ],
            options={
                'verbose_name': 'Pre-solicitud contratista',
                'verbose_name_plural': 'Pre-solicitudes contratistas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='contractor_app_org_status_idx'), models.Index(fields=['document_number'], name='contractor_app_doc_idx')],
            },
        ),
    ]
