# Generated by Django 5.2 on 2026-05-25 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_contractorapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contrato_actual', 'Contrato actual'), ('documento_identidad_frontal', 'Documento identidad frontal'), ('documento_identidad_reverso', 'Documento identidad reverso'), ('certificado_bancario', 'Certificado bancario')], max_length=60)),
                ('file', models.FileField(upload_to='contractors/applications/documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='RECIBIDO', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contractors.contractorapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contractor_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de pre-solicitud contratista',
                'verbose_name_plural': 'Documentos de pre-solicitud contratista',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['application', 'document_type'], name='contractor_doc_app_type_idx'), models.Index(fields=['status', 'uploaded_at'], name='contractor_doc_status_idx')],
            },
        ),
    ]
