# Generated by Django 5.2 on 2026-05-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_contractorapplicationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorapplication',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_contractor_application', 'Puede revisar pre-solicitudes contratistas')], 'verbose_name': 'Pre-solicitud contratista', 'verbose_name_plural': 'Pre-solicitudes contratistas'},
        ),
        migrations.AlterModelOptions(
            name='contractorapplicationdocument',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_review_contractor_document', 'Puede revisar documentos de pre-solicitud contratista')], 'verbose_name': 'Documento de pre-solicitud contratista', 'verbose_name_plural': 'Documentos de pre-solicitud contratista'},
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='notas_revision',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_contratista_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
