# Generated by Django 5.2 on 2026-05-26 03:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_alter_contractorapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionLaboralSolicitudContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=160)),
                ('tipo_contrato', models.CharField(choices=[('PRESTACION_SERVICIOS', 'Prestacion de servicios'), ('LABORAL', 'Laboral'), ('OTRO', 'Otro')], max_length=30)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
                ('valor_total_contrato', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_pagado_contrato', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_pendiente_cobrar', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('empresa_contratante_nombre', models.CharField(max_length=180)),
                ('empresa_contratante_nit', models.CharField(blank=True, max_length=40)),
                ('pagador_nombre', models.CharField(max_length=160)),
                ('pagador_email', models.EmailField(max_length=254)),
                ('pagador_telefono', models.CharField(blank=True, max_length=40)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_laboral', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Informacion laboral de solicitud contratista',
                'verbose_name_plural': 'Informacion laboral de solicitudes contratistas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo_contrato'], name='contr_info_tipo_idx'), models.Index(fields=['empresa_contratante_nombre'], name='contr_info_empresa_idx'), models.Index(fields=['fecha_fin_contrato'], name='contr_info_fecha_fin_idx')],
            },
        ),
    ]
