# Generated by Django 5.2 on 2026-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_informacionlaboralsolicitudcontratista'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapplication',
            name='escenario_credito',
            field=models.CharField(choices=[('NUEVO_CREDITO', 'Nuevo credito'), ('SEGUNDO_CREDITO', 'Segundo credito'), ('RECOGIDA_CARTERA', 'Recogida de cartera')], default='NUEVO_CREDITO', max_length=30),
        ),
    ]
