# Generated by Django 5.2 on 2026-05-27 01:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_contractorapplication_escenario_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='contractors.contractororganization'),
        ),
        migrations.CreateModel(
            name='ConfiguracionPortalContratistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(max_length=160)),
                ('host', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('color_primario', models.CharField(default='#0d6efd', max_length=20)),
                ('color_secundario', models.CharField(default='#6c757d', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contractors/portal/logos/')),
                ('correo_soporte', models.EmailField(blank=True, max_length=254)),
                ('texto_landing', models.TextField(blank=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plazo_minimo_meses', models.PositiveSmallIntegerField(default=1)),
                ('plazo_maximo_meses', models.PositiveSmallIntegerField()),
                ('tasa_mensual', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('tasa_comision', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('comision_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tasa_iva', models.DecimalField(decimal_places=4, default=Decimal('19.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion portal contratistas',
                'verbose_name_plural': 'Configuraciones portal contratistas',
                'ordering': ['host'],
                'indexes': [models.Index(fields=['host', 'activo'], name='contr_portal_host_idx'), models.Index(fields=['slug', 'activo'], name='contr_portal_slug_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('host',), name='unique_active_contractor_portal_host')],
            },
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='configuracion_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='contractors.configuracionportalcontratistas'),
        ),
    ]
