# Generated by Django 5.2 on 2026-05-27 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_alter_contractorapplication_organization_and_more'),
        ('gestion_creditos', '0034_add_risk_diagnostic_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionlaboralsolicitudcontratista',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_contratista_laborales', to='gestion_creditos.empresa'),
        ),
        migrations.AlterField(
            model_name='informacionlaboralsolicitudcontratista',
            name='empresa_contratante_nombre',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='informacionlaboralsolicitudcontratista',
            name='pagador_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='informacionlaboralsolicitudcontratista',
            name='pagador_nombre',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='informacionlaboralsolicitudcontratista',
            index=models.Index(fields=['empresa'], name='contr_info_empresa_fk_idx'),
        ),
    ]
