# Generated by Django 5.2 on 2026-05-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0010_informacionlaboralsolicitudcontratista_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapplication',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_contratista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contractorapplication',
            index=models.Index(fields=['configuracion_portal', 'usuario', 'created_at'], name='contractor_app_portal_user_idx'),
        ),
    ]
